'use client';
import {useState,type ComponentProps,type CSSProperties} from 'react';
import * as stylex from '@stylexjs/stylex';
type Styled<P> = Omit<P,'className'> & {className?:never;xstyle?:stylex.StyleXStyles};
const ring='0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 2px var(--background), 0 0 0 0 #0000';
// StyleX enum types omit valid var() values; the variable resolves only to darken/lighten.
const styles=stylex.create({
 avatar:{display:'flex',flexShrink:0,userSelect:'none',width:{default:'2rem',':is([data-size="sm"])':'1.5rem',':is([data-size="lg"])':'2.5rem'},height:{default:'2rem',':is([data-size="sm"])':'1.5rem',':is([data-size="lg"])':'2.5rem'},borderRadius:{default:'calc(infinity * 1px)','::after':'calc(infinity * 1px)'},content:{default:null,'::after':'""'},position:{default:'relative','::after':'absolute'},inset:{default:null,'::after':0},borderWidth:{default:null,'::after':1},borderColor:{default:null,'::after':'var(--border)'},'--ariax-avatar-blend':{default:'darken',':is(.dark *)':'lighten'},mixBlendMode:{default:null,'::after':'var(--ariax-avatar-blend)' as 'darken' | 'lighten'}},
 image:{aspectRatio:'1 / 1',width:'100%',height:'100%',objectFit:'cover',borderRadius:'calc(infinity * 1px)',display:{default:null,':is([data-state="error"])':'none'}},
 fallback:{backgroundColor:'var(--muted)',color:'var(--muted-foreground)',borderRadius:'calc(infinity * 1px)',display:{default:'flex',':is(.ariax-avatar-image ~ *)':'none',':is(.ariax-avatar-image[data-state="error"] ~ *)':'flex'},width:'100%',height:'100%',alignItems:'center',justifyContent:'center',fontSize:{default:'.875rem',':is(.ariax-avatar[data-size="sm"] *)':'.75rem'},lineHeight:{default:'calc(1.25 / .875)',':is(.ariax-avatar[data-size="sm"] *)':'calc(1 / .75)'}},
 badge:{position:'absolute',insetInlineEnd:0,bottom:0,zIndex:10,display:'inline-flex',alignItems:'center',justifyContent:'center',borderRadius:'calc(infinity * 1px)',backgroundBlendMode:'color',backgroundColor:'var(--primary)',color:'var(--primary-foreground)',boxShadow:ring,userSelect:'none',width:{default:null,':is(.ariax-avatar[data-size="sm"] *)':'.5rem',':is(.ariax-avatar[data-size="default"] *)':'.625rem',':is(.ariax-avatar[data-size="lg"] *)':'.75rem'},height:{default:null,':is(.ariax-avatar[data-size="sm"] *)':'.5rem',':is(.ariax-avatar[data-size="default"] *)':'.625rem',':is(.ariax-avatar[data-size="lg"] *)':'.75rem'}},
 group:{display:'flex'},
 count:{backgroundColor:'var(--muted)',color:'var(--muted-foreground)',width:{default:'2rem',':is(.ariax-avatar-group:has([data-size="lg"]):not(:has([data-size="sm"])) *)':'2.5rem',':is(.ariax-avatar-group:has([data-size="sm"]) *)':'1.5rem'},height:{default:'2rem',':is(.ariax-avatar-group:has([data-size="lg"]):not(:has([data-size="sm"])) *)':'2.5rem',':is(.ariax-avatar-group:has([data-size="sm"]) *)':'1.5rem'},borderRadius:'calc(infinity * 1px)',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',position:'relative',display:'flex',flexShrink:0,alignItems:'center',justifyContent:'center',boxShadow:ring},
});
function applied(base:stylex.StyleXStyles,xstyle:stylex.StyleXStyles|undefined,style:CSSProperties|undefined,marker?:string){const sx=stylex.props(base,xstyle);return {className:[marker,sx.className].filter(Boolean).join(' '),style:{...sx.style,...style}};}
export function Avatar({className:_,size='default',xstyle,style,...props}:Styled<ComponentProps<'div'>>&{size?:'default'|'sm'|'lg'}){return <div data-slot="avatar" data-size={size} {...applied(styles.avatar,xstyle,style,'ariax-avatar')} {...props}/>;}
export function AvatarImage({className:_,xstyle,style,...props}:Styled<ComponentProps<'img'>>){const[state,setState]=useState<'loading'|'loaded'|'error'>(props.src?'loading':'error');return <img data-slot="avatar-image" alt={props.alt||''} data-state={state} onLoad={()=>setState('loaded')} onError={()=>setState('error')} {...applied(styles.image,xstyle,style,'ariax-avatar-image')} {...props}/>;}
export function AvatarFallback({className:_,xstyle,style,...props}:Styled<ComponentProps<'div'>>){return <div data-slot="avatar-fallback" {...applied(styles.fallback,xstyle,style)} {...props}/>;}
export function AvatarBadge({className:_,xstyle,style,...props}:Styled<ComponentProps<'span'>>){return <span data-slot="avatar-badge" {...applied(styles.badge,xstyle,style,'ariax-avatar-badge')} {...props}/>;}
export function AvatarGroup({className:_,xstyle,style,...props}:Styled<ComponentProps<'div'>>){return <div data-slot="avatar-group" {...applied(styles.group,xstyle,style,'ariax-avatar-group')} {...props}/>;}
export function AvatarGroupCount({className:_,xstyle,style,...props}:Styled<ComponentProps<'div'>>){return <div data-slot="avatar-group-count" {...applied(styles.count,xstyle,style,'ariax-avatar-group-count')} {...props}/>;}
