'use client';
import * as React from 'react';
import * as stylex from '@stylexjs/stylex';
import { Button as ButtonPrimitive, Collection, ComboBox as ComboBoxPrimitive, ComboBoxStateContext, ComboBoxValue, composeRenderProps, Group, Header, Input, ListBoxItem, ListBox, ListBoxSection, Popover, Separator, TagGroup, TagList, Tag, type ComboBoxProps, type ComboBoxValueProps, type ListBoxProps, type ListBoxItemProps, type ListBoxSectionProps, type TagListProps, type TagProps, type InputProps } from 'react-aria-components';
import { ChevronDownIcon, CheckIcon, XIcon } from 'lucide-react';
import { Button } from './button';
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from './input-group';
import { animationStyles } from './animations.stylex';
type Styled<P> = Omit<P,'className'> & { className?: never; xstyle?: stylex.StyleXStyles };
export function Combobox<T extends object,M extends 'single'|'multiple'='single'>({className:_,xstyle,style,...props}:Styled<ComboBoxProps<T,M>>) {const sx=stylex.props(xstyle);return <ComboBoxPrimitive {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function ComboboxValue<T>({className:_,xstyle,style,...props}:Styled<ComboBoxValueProps<T>>) {const sx=stylex.props(xstyle);return <ComboBoxValue data-slot="combobox-value" {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function ComboboxTrigger({className:_,xstyle,style,children,...props}:Styled<Omit<React.ComponentProps<typeof ButtonPrimitive>,'children'>>&{children?:React.ReactNode}) {const sx=stylex.props(xstyle);return <ButtonPrimitive data-slot="combobox-trigger" {...props} className={['ariax-combobox-trigger',sx.className].filter(Boolean).join(' ')} style={composeRenderProps(style,value=>({...sx.style,...value}))}>{children}<ChevronDownIcon {...elementStyle(styles.triggerIcon)}/></ButtonPrimitive>;}
function ComboboxClear(props:React.ComponentProps<typeof InputGroupButton>){const state=React.useContext(ComboBoxStateContext);if(state?.inputValue==='')return null;return <InputGroupButton data-slot="combobox-clear" variant="ghost" size="icon-xs" aria-label="Clear" onPress={()=>state?.setValue(null)} slot={null} {...props}><XIcon {...elementStyle(styles.pointerIcon)}/></InputGroupButton>;}
export function ComboboxInput({className:_,xstyle,children,disabled=false,showTrigger=true,showClear=false,...props}:Styled<React.ComponentProps<'input'>>&{showTrigger?:boolean;showClear?:boolean}) {return <InputGroup xstyle={[styles.inputBox,xstyle]}><InputGroupInput disabled={disabled} {...props}/><InputGroupAddon align="inline-end">{showTrigger&&<InputGroupButton size="icon-xs" variant="ghost" data-slot="combobox-trigger" xstyle={styles.inputTrigger} isDisabled={disabled}><ChevronDownIcon {...elementStyle(styles.triggerIcon)}/></InputGroupButton>}{showClear&&<ComboboxClear isDisabled={disabled}/>}</InputGroupAddon>{children}</InputGroup>;}
export function ComboboxContent({className:_,xstyle,style,placement='bottom',offset=6,crossOffset=0,anchor,...props}:Styled<Omit<React.ComponentProps<typeof Popover>,'children'>>&{children?:React.ReactNode;anchor?:React.RefObject<HTMLDivElement|null>}) {const sx=stylex.props(animationStyles.overlay,styles.content,xstyle);return <Popover data-slot="combobox-content" placement={placement} offset={offset} crossOffset={crossOffset} triggerRef={anchor} {...props} className={['ariax-combobox-content',sx.className].join(' ')} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function ComboboxList<T extends object>({className:_,xstyle,style,...props}:Styled<ListBoxProps<T>>) {const sx=stylex.props(styles.list,xstyle);return <ListBox data-slot="combobox-list" {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function ComboboxItem<T extends object>({className:_,xstyle,style,children,...props}:Styled<ListBoxItemProps<T>>) {const sx=stylex.props(styles.item,xstyle);return <ListBoxItem data-slot="combobox-item" textValue={typeof children==='string'?children:undefined} {...props} className={['ariax-combobox-item',sx.className].join(' ')} style={composeRenderProps(style,value=>({...sx.style,...value}))}>{composeRenderProps(children,(children,{isSelected})=><>{children}<span {...elementStyle(styles.indicator)}>{isSelected?<CheckIcon {...elementStyle(styles.pointerIcon)}/>:null}</span></>)}</ListBoxItem>;}
export function ComboboxGroup<T extends object>({className:_,xstyle,style,...props}:Styled<ListBoxSectionProps<T>>) {const sx=stylex.props(xstyle);return <ListBoxSection data-slot="combobox-group" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function ComboboxLabel({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Header>>) {const sx=stylex.props(styles.label,xstyle);return <Header data-slot="combobox-label" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function ComboboxEmpty({className:_,xstyle,style,...props}:Styled<React.ComponentProps<'div'>>) {const sx=stylex.props(styles.empty,xstyle);return <div data-slot="combobox-empty" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function ComboboxSeparator({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Separator>>) {const sx=stylex.props(styles.separator,xstyle);return <Separator data-slot="combobox-separator" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function ComboboxChips({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Group>>) {const sx=stylex.props(styles.chips,xstyle);return <Group data-slot="combobox-chips" {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function ComboboxChipList<T extends object>({className:_,xstyle,style,...props}:Styled<Omit<TagListProps<T>,'items'>>) {const sx=stylex.props(styles.contents,xstyle);const list=stylex.props(styles.contents);return <ComboBoxValue<T> {...elementStyle(styles.contents)}>{({selectedItems,state})=><TagGroup data-slot="combobox-chip-list" className={sx.className} style={sx.style} onRemove={keys=>{if(Array.isArray(state.value))state.setValue(state.value.filter(key=>!keys.has(key)));}}><TagList className={list.className} items={selectedItems.filter(item=>item!=null)} {...props} style={composeRenderProps(style,value=>({...list.style,...value}))}/></TagGroup>}</ComboBoxValue>;}
export function ComboboxChip({className:_,xstyle,style,children,showRemove=true,...props}:Styled<Omit<TagProps,'children'>>&{children?:React.ReactNode;showRemove?:boolean}) {const sx=stylex.props(styles.chip,xstyle);return <Tag data-slot="combobox-chip" {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}>{children}{showRemove&&<Button slot="remove" variant="ghost" size="icon-xs" xstyle={styles.chipRemove} data-slot="combobox-chip-remove"><XIcon {...elementStyle(styles.pointerIcon)}/></Button>}</Tag>;}
export function ComboboxChipsInput({className:_,xstyle,style,...props}:Styled<InputProps>) {const state=React.useContext(ComboBoxStateContext);const sx=stylex.props(styles.chipInput,xstyle);return <Input data-slot="combobox-chip-input" onKeyDown={event=>{if(event.key==='Backspace'&&event.currentTarget.value===''&&Array.isArray(state?.value)&&state.value.length>0){event.preventDefault();state.setValue(state.value.slice(0,-1));}}} {...props} className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function useComboboxAnchor(){return React.useRef<HTMLDivElement|null>(null);}
export {Collection as ComboboxCollection};
function elementStyle(value:stylex.StyleXStyles){const {className,style}=stylex.props(value);return {className,style};}
const ring='0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 3px var(--ariax-combobox-ring), 0 0 0 0 #0000';
const invalid=':has([aria-invalid="true"])';
const styles=stylex.create({
 inputBox:{width:'auto'},inputTrigger:{display:{default:'flex',':is([data-slot="input-group"]:has([data-slot="combobox-clear"]) *)':'none'},backgroundColor:{default:null,':hover':{default:null,'@media (hover: hover)':'var(--muted)'},':is([aria-expanded="true"])':'var(--muted)',':is(.dark *):hover':{default:null,'@media (hover: hover)':'color-mix(in oklab, var(--muted) 50%, transparent)'},':is([data-pressed])':'transparent',':hover:is([data-pressed])':{default:null,'@media (hover: hover)':'transparent'},':is(.dark *)[data-pressed]:hover':{default:null,'@media (hover: hover)':'color-mix(in oklab, var(--muted) 50%, transparent)'}}},
 triggerIcon:{color:'var(--muted-foreground)',width:'calc(var(--ariax-spacing, .25rem) * 4)',height:'calc(var(--ariax-spacing, .25rem) * 4)',pointerEvents:'none'},pointerIcon:{pointerEvents:'none'},
 content:{position:'relative',isolation:'isolate',zIndex:50,width:'var(--trigger-width)',transformOrigin:'var(--trigger-anchor-point)',overflow:'hidden',maxHeight:'calc(var(--ariax-spacing, .25rem) * 72)',minWidth:'calc(var(--ariax-spacing, .25rem) * 36)',borderRadius:'var(--radius)',backgroundColor:'var(--popover)',color:'var(--popover-foreground)',boxShadow:'0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), 0 4px 6px -1px rgb(0 0 0 / .1), 0 2px 4px -2px rgb(0 0 0 / .1)',transitionDuration:'100ms',animationDuration:{default:null,':is([data-entering], [data-exiting])':'100ms'},animationTimingFunction:{default:null,':is([data-entering], [data-exiting])':'ease'},'--ariax-enter-opacity':{default:1,':is([data-entering])':0},'--ariax-enter-scale':{default:1,':is([data-entering])':.95},'--ariax-exit-opacity':{default:1,':is([data-exiting])':0},'--ariax-exit-scale':{default:1,':is([data-exiting])':.95},'--ariax-enter-x':{default:'0px',':is([data-placement="left"])':'calc(var(--ariax-spacing, .25rem) * 2)',':is([data-placement="right"])':'calc(var(--ariax-spacing, .25rem) * -2)'},'--ariax-enter-y':{default:'0px',':is([data-placement="bottom"])':'calc(var(--ariax-spacing, .25rem) * -2)',':is([data-placement="top"])':'calc(var(--ariax-spacing, .25rem) * 2)'}},
 list:{scrollbarWidth:'none',display:{default:null,'::-webkit-scrollbar':'none'},scrollPaddingBlock:'calc(var(--ariax-spacing, .25rem) * 1)',padding:{default:'calc(var(--ariax-spacing, .25rem) * 1)',':is([data-empty])':0},maxHeight:'inherit',overflowY:'auto',overscrollBehavior:'contain'},
 item:{position:'relative',display:'flex',width:'100%',cursor:'default',alignItems:'center',outlineStyle:{default:'none','@media (forced-colors: active)':'solid'},outlineWidth:{default:null,'@media (forced-colors: active)':2},outlineColor:{default:null,'@media (forced-colors: active)':'transparent'},outlineOffset:{default:null,'@media (forced-colors: active)':2},userSelect:'none',gap:'calc(var(--ariax-spacing, .25rem) * 2)',borderRadius:'calc(var(--radius) * .8)',paddingBlock:'calc(var(--ariax-spacing, .25rem) * 1)',paddingInlineStart:'calc(var(--ariax-spacing, .25rem) * 1.5)',paddingInlineEnd:'calc(var(--ariax-spacing, .25rem) * 8)',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',pointerEvents:{default:null,':is([data-disabled])':'none'},opacity:{default:null,':is([data-disabled])':.5},backgroundColor:{default:null,':is([data-highlighted])':'var(--accent)',':is(.ariax-combobox-content *)[data-focused]':'color-mix(in oklab, var(--foreground) 10%, transparent)'},color:{default:null,':is([data-highlighted])':'var(--accent-foreground)',':is([data-focused])':'var(--accent-foreground)'}},
 indicator:{pointerEvents:'none',position:'absolute',insetInlineEnd:'calc(var(--ariax-spacing, .25rem) * 2)',display:'flex',width:'calc(var(--ariax-spacing, .25rem) * 4)',height:'calc(var(--ariax-spacing, .25rem) * 4)',alignItems:'center',justifyContent:'center'},label:{color:'var(--muted-foreground)',paddingInline:'calc(var(--ariax-spacing, .25rem) * 2)',paddingBlock:'calc(var(--ariax-spacing, .25rem) * 1.5)',fontSize:'.75rem',lineHeight:'calc(1 / .75)'},
 empty:{color:'var(--muted-foreground)',display:{default:'none',':is([data-slot="combobox-list"][data-empty] *)':'flex'},width:'100%',justifyContent:'center',paddingBlock:'calc(var(--ariax-spacing, .25rem) * 2)',textAlign:'center',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)'},separator:{backgroundColor:'var(--border)',marginInline:'calc(var(--ariax-spacing, .25rem) * -1)',marginBlock:'calc(var(--ariax-spacing, .25rem) * 1)',height:'1px'},
 contents:{display:'contents'},
 chips:{display:'flex',minHeight:'calc(var(--ariax-spacing, .25rem) * 8)',flexWrap:'wrap',alignItems:'center',gap:'calc(var(--ariax-spacing, .25rem) * 1)',borderRadius:'var(--radius)',borderWidth:'1px',borderStyle:'solid',backgroundClip:'padding-box',backgroundColor:{default:'transparent',':is(.dark *)':'color-mix(in oklab, var(--input) 30%, transparent)'},borderColor:{default:'var(--input)',':focus-within':'var(--ring)',[invalid]:'var(--destructive)',':is(.dark *):has([aria-invalid="true"])':'color-mix(in oklab, var(--destructive) 50%, transparent)'},paddingInline:{default:'calc(var(--ariax-spacing, .25rem) * 2.5)',':has([data-slot="combobox-chip"])':'calc(var(--ariax-spacing, .25rem) * 1)'},paddingBlock:'calc(var(--ariax-spacing, .25rem) * 1)',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',transitionProperty:'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to',transitionDuration:'150ms',transitionTimingFunction:'cubic-bezier(0.4, 0, 0.2, 1)','--ariax-combobox-ring':{default:'color-mix(in oklab, var(--ring) 50%, transparent)',[invalid]:'color-mix(in oklab, var(--destructive) 20%, transparent)',':is(.dark *):has([aria-invalid="true"])':'color-mix(in oklab, var(--destructive) 40%, transparent)'},boxShadow:{default:null,':focus-within':ring,[invalid]:ring}},
 chip:{backgroundColor:'var(--muted)',color:'var(--foreground)',display:'flex',height:'calc(var(--ariax-spacing, .25rem) * 5.25)',width:'fit-content',alignItems:'center',justifyContent:'center',gap:'calc(var(--ariax-spacing, .25rem) * 1)',borderRadius:'calc(var(--radius) * .6)',paddingInlineStart:'calc(var(--ariax-spacing, .25rem) * 1.5)',paddingInlineEnd:{default:'calc(var(--ariax-spacing, .25rem) * 1.5)',':has([data-slot="combobox-chip-remove"])':0},fontSize:'.75rem',lineHeight:'calc(1 / .75)',fontWeight:500,whiteSpace:'nowrap',pointerEvents:{default:null,':has(:disabled)':'none'},cursor:{default:null,':has(:disabled)':'not-allowed'},opacity:{default:null,':has(:disabled)':.5}},
 chipRemove:{marginInlineStart:'calc(var(--ariax-spacing, .25rem) * -1)',opacity:{default:.5,':hover':{default:null,'@media (hover: hover)':1}}},chipInput:{minWidth:'calc(var(--ariax-spacing, .25rem) * 16)',flex:'1 1 0%',outlineStyle:'none'},
});
