'use client';
import type * as React from 'react';
import * as stylex from '@stylexjs/stylex';
import {Autocomplete,Collection,composeRenderProps,Header,Input,Menu,MenuItem,MenuSection,SearchField,Separator,useFilter,type AutocompleteProps,type InputProps,type MenuItemProps,type MenuProps,type MenuSectionProps,type SeparatorProps} from 'react-aria-components';
import {SearchIcon,CheckIcon} from 'lucide-react';
import {Dialog,DialogHeader,DialogTitle,DialogDescription} from './dialog';
import {InputGroup,InputGroupAddon} from './input-group';
type Custom<P>=Omit<P,'className'>&{className?:never;xstyle?:stylex.StyleXStyles};
export type CommandProps=Custom<Omit<AutocompleteProps,'style'>> & {dir?:React.HTMLAttributes<HTMLDivElement>['dir'];style?:React.CSSProperties};
export type CommandDialogProps=Custom<Omit<React.ComponentProps<typeof Dialog>,'children'|'isOpen'|'onOpenChange'>>&{title?:string;description?:string;open?:boolean;onOpenChange?:(open:boolean)=>void;showCloseButton?:boolean;children:React.ReactNode};
export function Command({className:_,xstyle,dir,style,...props}:CommandProps){const{contains}=useFilter({sensitivity:'base'});const sx=stylex.props(styles.root,xstyle);return <div data-slot="command" dir={dir} className={sx.className} style={{...sx.style,...style}}><Autocomplete {...props} filter={props.filter||contains}>{props.children}</Autocomplete></div>;}
export function CommandDialog({title='Command Palette',description='Search for a command to run...',children,open,onOpenChange,className:_,xstyle,showCloseButton=false,...props}:CommandDialogProps){return <Dialog isOpen={open} onOpenChange={onOpenChange} xstyle={[styles.dialog,xstyle]} showCloseButton={showCloseButton} isDismissable {...props}><DialogHeader xstyle={styles.srOnly}><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{children}</Dialog>;}
export function CommandInput({className:_,xstyle,style,...props}:Custom<InputProps>){const sx=stylex.props(styles.input,xstyle);return <SearchField autoFocus aria-label={props.placeholder||'Search'} data-slot="command-input-wrapper" className={stylex.props(styles.wrapper).className}><InputGroup xstyle={styles.inputGroup}><Input {...props} data-slot="command-input" className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/><InputGroupAddon xstyle={styles.addon}><SearchIcon className={stylex.props(styles.searchIcon).className}/></InputGroupAddon></InputGroup></SearchField>;}
export function CommandList<T extends object>({className:_,xstyle,style,...props}:Custom<MenuProps<T>>){const sx=stylex.props(styles.list,xstyle);return <Menu {...props} data-slot="command-list" className={sx.className} style={composeRenderProps(style,value=>({...sx.style,...value}))}/>;}
export function CommandEmpty({className:_,xstyle,style,...props}:Custom<React.ComponentProps<'div'>>){const sx=stylex.props(styles.empty,xstyle);return <div data-slot="command-empty" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function CommandGroup<T extends object>({className:_,xstyle,style,children,items,heading,...props}:Custom<MenuSectionProps<T>>&{heading?:string}){const sx=stylex.props(styles.group,xstyle);return <MenuSection data-slot="command-group" {...props} className={['ariax-command-group',sx.className].join(' ')} style={{...sx.style,...style}}>{heading&&<Header cmdk-group-heading="">{heading}</Header>}<Collection items={items}>{children}</Collection></MenuSection>;}
export function CommandSeparator({className:_,xstyle,style,...props}:Custom<SeparatorProps>){const sx=stylex.props(styles.separator,xstyle);return <Separator data-slot="command-separator" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
export function CommandItem<T extends object>({className:_,xstyle,style,children,textValue,...props}:Custom<MenuItemProps<T>>){const sx=stylex.props(styles.item,xstyle);return <MenuItem {...props} data-slot="command-item" className={['ariax-command-item',sx.className].join(' ')} style={composeRenderProps(style,value=>({...sx.style,...value}))} textValue={textValue||(typeof children==='string'?children:undefined)}>{composeRenderProps(children,children=><>{children}<CheckIcon className={stylex.props(styles.indicator).className}/></>)}</MenuItem>;}
export function CommandShortcut({className:_,xstyle,style,...props}:Custom<React.ComponentProps<'span'>>){const sx=stylex.props(styles.shortcut,xstyle);return <span data-slot="command-shortcut" {...props} className={sx.className} style={{...sx.style,...style}}/>;}
const selected=':is([data-selected="true"],[data-focused])';
const styles=stylex.create({
 root:{display:'flex',width:'100%',height:'100%',flexDirection:'column',overflow:'hidden',backgroundColor:'var(--popover)',color:'var(--popover-foreground)',borderRadius:'calc(var(--radius) * 1.4)',padding:'.25rem'},
 dialog:{top:'calc(100% / 3)',translate:{default:'-50% 0',':dir(rtl)':'50% 0'},overflow:'hidden',padding:0,borderRadius:'calc(var(--radius) * 1.4)'},
 srOnly:{position:'absolute',width:1,height:1,padding:0,margin:-1,overflow:'hidden',clipPath:'inset(50%)',whiteSpace:'nowrap',borderWidth:0},
 wrapper:{padding:'.25rem',paddingBottom:0},
 inputGroup:{height:'2rem',borderRadius:'var(--radius)',backgroundColor:{default:'color-mix(in oklab, var(--input) 30%, transparent)',':is(.dark *)':'color-mix(in oklab, var(--input) 30%, transparent)',':has(:disabled)':'color-mix(in oklab, var(--input) 50%, transparent)',':is(.dark *):has(:disabled)':'color-mix(in oklab, var(--input) 80%, transparent)'},borderColor:{default:'color-mix(in oklab, var(--input) 30%, transparent)',':has([data-slot][aria-invalid="true"])':'var(--destructive)'},boxShadow:{default:'0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000',':has([data-slot][aria-invalid="true"])':'0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 3px var(--ariax-group-ring), 0 0 0 0 #0000'}},
 addon:{paddingInlineStart:'.5rem'},
 searchIcon:{width:'1rem',height:'1rem',flexShrink:0,opacity:.5},
 input:{width:'100%',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',outlineStyle:{default:'none','@media (forced-colors: active)':'solid'},outlineWidth:{default:null,'@media (forced-colors: active)':2},outlineColor:{default:null,'@media (forced-colors: active)':'transparent'},outlineOffset:{default:null,'@media (forced-colors: active)':2},cursor:{default:null,':disabled':'not-allowed'},opacity:{default:null,':disabled':.5},display:{default:null,'::-webkit-search-cancel-button':'none'}},
 list:{overflowX:'hidden',overflowY:'auto',scrollbarWidth:'none',display:{default:null,'::-webkit-scrollbar':'none'},maxHeight:'18rem',scrollPaddingBlock:'.25rem',outlineStyle:'none'},
 empty:{paddingBlock:'1.5rem',textAlign:'center',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)'},
 group:{color:'var(--foreground)',overflow:'hidden',padding:'.25rem'},
 separator:{backgroundColor:'var(--border)',marginInline:'-.25rem',height:1},
 item:{position:'relative',display:'flex',cursor:'default',alignItems:'center',gap:'.5rem',borderRadius:{default:'calc(var(--radius) * .6)',':is([data-slot="dialog-content"] *)':'var(--radius)'},paddingInline:'.5rem',paddingBlock:'.375rem',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',outlineStyle:{default:'none','@media (forced-colors: active)':'solid'},outlineWidth:{default:null,'@media (forced-colors: active)':2},outlineColor:{default:null,'@media (forced-colors: active)':'transparent'},outlineOffset:{default:null,'@media (forced-colors: active)':2},userSelect:'none',backgroundColor:{default:null,[selected]:'var(--muted)'},color:{default:null,[selected]:'var(--foreground)'},pointerEvents:{default:null,':is([data-disabled="true"])':'none'},opacity:{default:null,':is([data-disabled="true"])':.5}},
 indicator:{marginInlineStart:'auto',opacity:{default:0,':is(.ariax-command-item[data-checked="true"] *)':1},display:{default:null,':is(.ariax-command-item:has([data-slot="command-shortcut"]) *)':'none'}},
 shortcut:{marginInlineStart:'auto',fontSize:'.75rem',lineHeight:'calc(1 / .75)',letterSpacing:'.1em',color:{default:'var(--muted-foreground)',':is(.ariax-command-item[data-selected="true"] *, .ariax-command-item[data-focused] *)':'var(--foreground)'}},
});
