'use client';
import * as React from 'react';
import * as stylex from '@stylexjs/stylex';
import {composeRenderProps,Dialog as Primitive,DialogTrigger as Trigger,Heading,ModalOverlay,Modal,type DialogProps as DialogPrimitiveProps,type DialogTriggerProps as DialogTriggerPrimitiveProps} from 'react-aria-components';
import {Button,type ButtonProps} from './button';
import {XIcon} from 'lucide-react';
import {RenderStylesContext} from './render-styles.internal';
import {animationStyles} from './animations.stylex';
export type {DialogPrimitiveProps,DialogTriggerPrimitiveProps};
type Custom={xstyle?:stylex.StyleXStyles;className?:never};
export type DialogOverlayProps=Omit<React.ComponentProps<typeof ModalOverlay>,'className'|'children'> & Custom & {children:React.ReactNode};
export type DialogProps=DialogOverlayProps & {showCloseButton?:boolean;isDismissable?:boolean};
const styles=stylex.create({
 overlay:{position:'fixed',inset:0,isolation:'isolate',zIndex:50,backgroundColor:'color-mix(in oklab, black 10%, transparent)',backdropFilter:{default:null,'@supports (backdrop-filter: blur(1px))':'blur(4px)'},transitionDuration:'100ms',animationDuration:{default:null,':is([data-entering],[data-exiting])':'100ms'},animationTimingFunction:{default:null,':is([data-entering],[data-exiting])':'ease'},'--ariax-enter-opacity':{default:1,':is([data-entering])':0},'--ariax-exit-opacity':{default:1,':is([data-exiting])':0}},
 content:{position:'fixed',top:'50%',insetInlineStart:'50%',zIndex:50,width:'100%',translate:{default:'-50% -50%',':dir(rtl)':'50% -50%'},outlineStyle:'none',display:'grid',maxWidth:{default:'calc(100% - 2rem)','@media (width >= 40rem)':'24rem'},gap:'1rem',borderRadius:'calc(var(--radius) * 1.4)',padding:'1rem',fontSize:'0.875rem',lineHeight:'calc(1.25 / 0.875)',backgroundColor:'var(--popover)',color:'var(--popover-foreground)',boxShadow:'0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 0 #0000, 0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), 0 0 0 0 #0000',transitionDuration:'100ms',animationDuration:{default:null,':is([data-entering],[data-exiting])':'100ms'},animationTimingFunction:{default:null,':is([data-entering],[data-exiting])':'ease'},'--ariax-enter-opacity':{default:1,':is([data-entering])':0},'--ariax-exit-opacity':{default:1,':is([data-exiting])':0},'--ariax-enter-scale':{default:1,':is([data-entering])':0.95},'--ariax-exit-scale':{default:1,':is([data-exiting])':0.95}},
 primitive:{display:'inherit',gap:'inherit',outlineStyle:'none'},close:{position:'absolute',top:'0.5rem',insetInlineEnd:'0.5rem'},srOnly:{position:'absolute',width:1,height:1,padding:0,margin:-1,overflow:'hidden',clipPath:'inset(50%)',whiteSpace:'nowrap',borderWidth:0},
 header:{display:'flex',flexDirection:'column',gap:'0.5rem'},footer:{display:'flex',flexDirection:{default:'column-reverse','@media (width >= 40rem)':'row'},justifyContent:{default:null,'@media (width >= 40rem)':'flex-end'},gap:'0.5rem',backgroundColor:'color-mix(in oklab, var(--muted) 50%, transparent)',marginInline:'-1rem',marginBottom:'-1rem',borderEndStartRadius:'calc(var(--radius) * 1.4)',borderEndEndRadius:'calc(var(--radius) * 1.4)',borderTopWidth:1,padding:'1rem'},title:{fontSize:'1rem',lineHeight:1,fontWeight:500},description:{color:'var(--muted-foreground)',fontSize:'0.875rem',lineHeight:'calc(1.25 / 0.875)'},
});
export function DialogTrigger(props:DialogTriggerPrimitiveProps){return <Trigger data-slot="dialog-trigger" {...props}/>;}
export function DialogClose({variant='outline',size='default',...props}:ButtonProps){return <Button slot="close" data-slot="dialog-close" variant={variant} size={size} {...props}/>;}
export function DialogOverlay({xstyle,style,className:_,children,...props}:DialogOverlayProps){const applied=stylex.props(animationStyles.overlay,styles.overlay,xstyle);return <ModalOverlay data-slot="dialog-overlay" {...props} className={applied.className} style={composeRenderProps(style,value=>({...applied.style,...value}))}>{children}</ModalOverlay>;}
export function Dialog({xstyle,className:_,children,showCloseButton=true,isDismissable=true,...props}:DialogProps){const content=stylex.props(animationStyles.overlay,styles.content,xstyle);const primitive=stylex.props(styles.primitive);const sr=stylex.props(styles.srOnly);return <DialogOverlay isDismissable={isDismissable} {...props}><Modal data-slot="dialog-content" className={content.className} style={content.style}><Primitive data-slot="dialog" className={primitive.className} style={primitive.style}>{children}{showCloseButton&&<DialogClose variant="ghost" size="icon-sm" xstyle={styles.close}><XIcon/><span className={sr.className} style={sr.style}>Close</span></DialogClose>}</Primitive></Modal></DialogOverlay>;}
type DivProps=Omit<React.ComponentProps<'div'>,'className'> & Custom;
export function DialogHeader({xstyle,style,className:_,...props}:DivProps){const a=stylex.props(styles.header,xstyle);return <div data-slot="dialog-header" {...props} className={a.className} style={{...a.style,...style}}/>;}
export function DialogFooter({xstyle,style,className:_,showCloseButton=false,children,...props}:DivProps & {showCloseButton?:boolean}){const a=stylex.props(styles.footer,xstyle);return <div data-slot="dialog-footer" {...props} className={a.className} style={{...a.style,...style}}>{children}{showCloseButton&&<DialogClose variant="outline">Close</DialogClose>}</div>;}
export function DialogTitle({xstyle,style,className:_,...props}:Omit<React.ComponentProps<typeof Heading>,'slot'|'className'> & Custom){const inherited=React.useContext(RenderStylesContext);const a=stylex.props(styles.title,inherited,xstyle);const element=<Heading slot="title" data-slot="dialog-title" {...props} className={a.className} style={{...a.style,...style}}/>;return inherited?<RenderStylesContext.Provider value={undefined}>{element}</RenderStylesContext.Provider>:element;}
export function DialogDescription({xstyle,style,className:_,...props}:Omit<DivProps,'slot'>){const inherited=React.useContext(RenderStylesContext);const a=stylex.props(styles.description,inherited,xstyle);const element=<div data-slot="dialog-description" {...props} className={['ariax-dialog-description',a.className].join(' ')} style={{...a.style,...style}}/>;return inherited?<RenderStylesContext.Provider value={undefined}>{element}</RenderStylesContext.Provider>:element;}
