'use client';
import * as React from 'react';
import * as stylex from '@stylexjs/stylex';
import {Questionnaire as Primitive} from '@shadcn/react/questionnaire';
import {CheckIcon} from 'lucide-react';
import {buttonProps,type ButtonProps} from './button';
import {RenderStylesContext} from './render-styles.internal';
import {styles} from './questionnaire.internal';
type Styled<P>=Omit<P,'className'>&{className?:never;xstyle?:stylex.StyleXStyles};
function dom(base:stylex.StyleXStyles,xstyle?:stylex.StyleXStyles,style?:React.CSSProperties){const sx=stylex.props(base,xstyle);return {className:sx.className,style:{...sx.style,...style}};}
export function Questionnaire({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Root>>){return <Primitive.Root data-slot="questionnaire" {...props} {...dom(styles.root,xstyle,style)}/>;}
export function QuestionnaireProgress({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Progress>>){return <Primitive.Progress data-slot="questionnaire-progress" {...props} {...dom(styles.progress,xstyle,style)}/>;}
export function QuestionnaireItem({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Item>>){return <Primitive.Item data-slot="questionnaire-item" {...props} {...dom(styles.item,xstyle,style)}/>;}
export function QuestionnaireTitle({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Title>>){const element=<Primitive.Title data-slot="questionnaire-title" {...props} {...dom(styles.title,xstyle,style)}/>;return React.isValidElement(props.render)&&typeof props.render.type!=='string'?<RenderStylesContext.Provider value={[styles.title,xstyle]}>{element}</RenderStylesContext.Provider>:element;}
export function QuestionnaireDescription({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Description>>){const element=<Primitive.Description data-slot="questionnaire-description" {...props} {...dom(styles.description,xstyle,style)}/>;return React.isValidElement(props.render)&&typeof props.render.type!=='string'?<RenderStylesContext.Provider value={[styles.description,xstyle]}>{element}</RenderStylesContext.Provider>:element;}
export function QuestionnaireChoices({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Choices>>){return <Primitive.Choices data-slot="questionnaire-choices" {...props} {...dom(styles.choices,xstyle,style)}/>;}
export function QuestionnaireError({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Error>>){return <Primitive.Error data-slot="questionnaire-error" {...props} {...dom(styles.error,xstyle,style)}/>;}
export function QuestionnaireActions({className:_,xstyle,style,...props}:Styled<React.ComponentProps<'div'>>){return <div data-slot="questionnaire-actions" {...props} {...dom(styles.actions,xstyle,style)}/>;}
export function QuestionnaireChoiceDescription({className:_,xstyle,style,...props}:Styled<React.ComponentProps<'span'>>){return <span data-slot="questionnaire-choice-description" {...props} {...dom(styles.choiceDescription,xstyle,style)}/>;}
export function QuestionnaireInput({className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Input>>){return <div data-slot="questionnaire-input-wrapper" {...dom(styles.inputWrapper)}><Primitive.Input data-slot="questionnaire-input" {...props} {...dom(styles.input,xstyle,style)}/></div>;}
export function QuestionnaireChoice({children,className:_,xstyle,style,...props}:Styled<React.ComponentProps<typeof Primitive.Choice>>){return <Primitive.Choice data-slot="questionnaire-choice" {...props} {...dom(styles.choice,xstyle,style)}><Primitive.ChoiceInput data-slot="questionnaire-choice-input" {...dom(styles.choiceInput)}/><span aria-hidden="true" data-slot="questionnaire-choice-indicator" {...dom(styles.indicator)}><span data-slot="questionnaire-choice-indicator-dot" {...dom(styles.dot)}/><CheckIcon data-slot="questionnaire-choice-indicator-check" {...dom(styles.check)}/></span><Primitive.ChoiceLabel data-slot="questionnaire-choice-label" {...dom(styles.label)}>{children}</Primitive.ChoiceLabel><Primitive.ChoiceShortcut data-slot="questionnaire-choice-shortcut" {...dom(styles.shortcut)}/></Primitive.Choice>;}
export function QuestionnairePrevious({children,className:_,xstyle,style,size='default',variant='outline',...props}:Styled<React.ComponentProps<typeof Primitive.Previous>>&Pick<ButtonProps,'size'|'variant'>){const sx=buttonProps({size,variant,xstyle:[styles.navigation,styles.previous,xstyle],style});return <Primitive.Previous data-slot="questionnaire-previous" data-size={size} data-variant={variant} {...props} {...sx}>{children??'Previous'}</Primitive.Previous>;}
export function QuestionnaireSkip({children,className:_,xstyle,style,size='default',variant='outline',...props}:Styled<React.ComponentProps<typeof Primitive.Skip>>&Pick<ButtonProps,'size'|'variant'>){const sx=buttonProps({size,variant,xstyle:[styles.navigation,styles.skip,xstyle],style});return <Primitive.Skip data-slot="questionnaire-skip" data-size={size} data-variant={variant} {...props} {...sx}>{children??'Skip'}</Primitive.Skip>;}
export function QuestionnaireNext({children,className:_,xstyle,style,size='default',variant='default',...props}:Styled<React.ComponentProps<typeof Primitive.Next>>&Pick<ButtonProps,'size'|'variant'>){const sx=buttonProps({size,variant,xstyle:[styles.navigation,styles.next,xstyle],style});return <Primitive.Next data-slot="questionnaire-next" data-size={size} data-variant={variant} {...props} {...sx}>{children??'Next'}</Primitive.Next>;}
export function QuestionnaireSubmit({children,className:_,xstyle,style,size='default',variant='default',...props}:Styled<React.ComponentProps<typeof Primitive.Submit>>&Pick<ButtonProps,'size'|'variant'>){const sx=buttonProps({size,variant,xstyle:[styles.navigation,styles.next,xstyle],style});return <Primitive.Submit data-slot="questionnaire-submit" data-size={size} data-variant={variant} {...props} {...sx}>{children??'Submit'}</Primitive.Submit>;}
