import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {compare} from './compare';
import {upstreamURL,stylexURL} from './servers';
test('Marker official document and explicit registry coverage',async({request})=>{
 const doc=await readFile('generated/upstream/shadcn/apps/v4/content/docs/components/aria/marker.mdx','utf8');const names=[...doc.matchAll(/<ComponentPreview\b[^>]*name="marker-([^"]+)"/g)].map(m=>m[1]);expect(names).toHaveLength(8);const entries=(await(await request.get(stylexURL+'/index.json')).json()).entries;
 for(const name of [...names,'usage'])expect(entries['components-marker--'+name]?.tags,name).toContain('parity');
 const registry=await readFile('generated/upstream/shadcn/apps/v4/registry/bases/aria/examples/marker-example.tsx','utf8');const functions=[...registry.matchAll(/^function (Marker\w+)\(/gm)].map(m=>m[1]);const mapping:Record<string,string>={MarkerExample:'registry-markers',MarkerBorder:'registry-border',MarkerSeparator:'registry-separator',MarkerAccordion:'registry-accordion'};
 expect(functions.sort()).toEqual([...Object.keys(mapping),'MarkerDrawer'].sort());for(const story of Object.values(mapping))expect(entries['components-marker--'+story]?.tags).toContain('parity');
 // This real dependency composition is tracked, not replaced by a fake Drawer.
 expect(await readFile('TODOLIST.md','utf8')).toContain('Marker — 구현·문서 예제 검증; Drawer 조합 통합 대기');
});
for(const theme of ['light','dark'])test(`Marker interactive render, accordion and customization / ${theme}`,async({browser},info)=>{const context=await browser.newContext({viewport:{width:1000,height:900}});const pages=await Promise.all([context.newPage(),context.newPage()]);try{for(const story of ['link-button','registry-accordion','customization']){
 await Promise.all(pages.map((p,i)=>p.goto(`${[upstreamURL,stylexURL][i]}/iframe.html?id=components-marker--${story}&globals=theme:${theme}`)));for(const p of pages)await expect(p.locator('#parity-root')).toBeVisible();
 if(story==='link-button'){for(const p of pages)await p.getByRole('link').hover();await compare(pages[0],pages[1],info,'link-hover');for(const p of pages){await p.mouse.move(0,0);await p.getByRole('button',{name:'Revert this change'}).focus();}await compare(pages[0],pages[1],info,'button-focus');for(const p of pages)await p.getByRole('button',{name:'Revert this change'}).press('Enter');await compare(pages[0],pages[1],info,'button-enter');}
 if(story==='registry-accordion'){for(const p of pages){await p.getByRole('button',{name:'Worked for 42s'}).click();await expect(p.getByRole('button',{name:'Worked for 42s'})).toHaveAttribute('aria-expanded','true');}await compare(pages[0],pages[1],info,'accordion-open');for(const p of pages)await p.getByRole('button',{name:'Worked for 42s'}).press('Space');await compare(pages[0],pages[1],info,'accordion-close');}
 if(story==='customization'){for(const p of pages){await p.getByRole('button',{name:'Change gap',exact:true}).click();await expect(p.locator('button[data-slot="marker"]')).toHaveCSS('gap','20px');await expect(p.locator('button[data-slot="marker"]')).toHaveCSS('padding','12px');await p.getByRole('button',{name:'Custom 0',exact:true}).click();await expect(p.getByRole('button',{name:'Custom 1',exact:true})).toBeVisible();}await compare(pages[0],pages[1],info,'dynamic-and-native');}
 }}finally{await context.close();}});
for(const theme of ['light','dark'])for(const dir of ['ltr','rtl'])test(`Marker shimmer actual 0/500/1000/2000ms and reduced motion / ${theme} / ${dir}`,async({browser},info)=>{const context=await browser.newContext({viewport:{width:1000,height:900}});const pages=await Promise.all([context.newPage(),context.newPage()]);try{await Promise.all(pages.map((p,i)=>p.goto(`${[upstreamURL,stylexURL][i]}/iframe.html?id=components-marker--${dir==='rtl'?'rtl':'shimmer'}&globals=theme:${theme}`)));for(const p of pages)await expect(p.locator('#parity-root')).toBeVisible();await compare(pages[0],pages[1],info,'initial');for(const time of [0,500,1000,2000]){for(const p of pages)await p.evaluate(async time=>{const animations=document.getAnimations().filter(a=>a.effect?.getTiming().duration===2000);if(!animations.length)throw Error('Missing real shimmer animation');for(const animation of animations){animation.pause();await animation.ready;animation.currentTime=time;}},time);await compare(pages[0],pages[1],info,'shimmer-'+time,true,false);}for(const p of pages){await p.emulateMedia({reducedMotion:'reduce'});await expect(p.getByText('Thinking...', {exact:true})).toHaveCSS('background-image','none');await expect(p.getByText('Thinking...', {exact:true})).toHaveCSS('animation-name','none');}await compare(pages[0],pages[1],info,'reduced-motion');}finally{await context.close();}});
test('Marker touch links do not apply hover-only colors',async({browser},info)=>{const context=await browser.newContext({viewport:{width:390,height:900},isMobile:true,hasTouch:true});const pages=await Promise.all([context.newPage(),context.newPage()]);try{await Promise.all(pages.map((p,i)=>p.goto(`${[upstreamURL,stylexURL][i]}/iframe.html?id=components-marker--link-button`)));for(const p of pages){await expect(p.getByRole('link')).toBeVisible();expect(await p.evaluate(()=>matchMedia('(hover: hover)').matches)).toBe(false);const link=p.getByRole('link');const color=await link.evaluate(n=>getComputedStyle(n).color);await link.tap();await expect(link).toHaveCSS('color',color);}await compare(pages[0],pages[1],info,'touch-link');}finally{await context.close();}});
