import{test,expect}from'@playwright/test';
import{readFile}from'node:fs/promises';
import{compare}from'./compare';
import{upstreamURL,stylexURL}from'./servers';
const documents=['demo','multiple','freeform','skip','shortcuts','validation','controlled','resume','conditional','navigation-state','progress','animated','card','dialog'];
test('Questionnaire official document and registry coverage',async({request})=>{const doc=await readFile('generated/upstream/shadcn/apps/v4/content/docs/components/aria/questionnaire.mdx','utf8');expect([...doc.matchAll(/<ComponentPreview\b[^>]*name="questionnaire-([^"]+)"/g)].map(m=>m[1])).toEqual(documents);const entries=(await(await request.get(stylexURL+'/index.json')).json()).entries;for(const id of [...documents,...['disabled','no-description','standalone','card','dialog'].map(s=>'registry-'+s)])expect(entries['components-questionnaire--'+id]?.tags,id).toContain('parity');});
for(const theme of ['light','dark'])for(const story of [...documents,'rtl','mobile'])test(`Questionnaire actual form flow / ${story} / ${theme}`,async({browser},info)=>{test.setTimeout(90_000);const context=await browser.newContext({viewport:{width:story==='mobile'?390:1000,height:900}});const pages=await Promise.all([context.newPage(),context.newPage()]);try{
 await Promise.all(pages.map((p,i)=>p.goto(`${[upstreamURL,stylexURL][i]}/iframe.html?id=components-questionnaire--${story}&globals=theme:${theme}`)));for(const p of pages){await expect(p.locator('#parity-root')).toBeVisible();if(story==='dialog')await p.getByRole('button',{name:'Open clarification'}).click();await expect(p.locator('[data-slot="questionnaire"]')).toBeVisible();}await compare(pages[0],pages[1],info,'initial');
 // Empty required answers exercise the engine's validation, error and focus state.
 if(!['resume','conditional','validation','navigation-state'].includes(story)){for(const p of pages){const next=p.locator('[data-slot="questionnaire-next"]:visible');const submit=p.locator('[data-slot="questionnaire-submit"]:visible');await (await next.count()?next:submit).click();}await compare(pages[0],pages[1],info,'required-validation');}
 if(story==='shortcuts'){for(const p of pages){await p.getByRole('combobox',{name:'Shortcut style'}).selectOption('numbers');await p.locator('[data-slot="questionnaire-choice-input"]:visible').first().focus();await p.keyboard.press('2');}await compare(pages[0],pages[1],info,'numeric-shortcut');}
 if(story==='conditional'){for(const p of pages)await p.getByRole('radio',{name:'Cloud workspace'}).check();await compare(pages[0],pages[1],info,'cloud-branch');}
 for(const p of pages){const active=p.locator('[data-slot="questionnaire-item"][data-active]');const choices=active.locator('input:is([type="radio"],[type="checkbox"]):enabled');if(await choices.count()){const choice=choices.first();await choice.check();await expect(choice).toBeChecked();if(story==='multiple'&&await choices.count()>1)await choices.nth(1).check();}const input=active.locator('[data-slot="questionnaire-input"]');if(await input.count()){await input.fill('A specific instruction');await expect(input).toHaveValue('A specific instruction');}}
 await compare(pages[0],pages[1],info,'answer');
 const values=await Promise.all(pages.map(p=>p.locator('[data-slot="questionnaire"]').evaluate(form=>Array.from(new FormData(form as HTMLFormElement).entries()))));expect(values[1]).toEqual(values[0]);expect(values[0].length).toBeGreaterThan(0);
 const nextExists=await pages[0].locator('[data-slot="questionnaire-next"]:visible').count();if(nextExists){const before=await pages[0].locator('[data-slot="questionnaire-item"][data-active]').locator('[data-slot="questionnaire-title"]').textContent();for(const p of pages){await p.locator('[data-slot="questionnaire-next"]:visible').click();await expect(p.locator('[data-slot="questionnaire-item"][data-active]').locator('[data-slot="questionnaire-title"]')).not.toHaveText(before!);}await compare(pages[0],pages[1],info,'next');for(const p of pages)await p.locator('[data-slot="questionnaire-previous"]:visible').click();await compare(pages[0],pages[1],info,'previous-preserves-answer');}
 if(story==='resume'){for(const p of pages)await p.locator('button[type="reset"]').click();await compare(pages[0],pages[1],info,'reset-saved-answers');}
 if(story==='dialog'){for(const p of pages){await p.keyboard.press('Escape');await expect(p.getByRole('dialog')).toBeHidden();await expect(p.getByRole('button',{name:'Open clarification'})).toBeFocused();}await compare(pages[0],pages[1],info,'dialog-close');}
 }finally{await context.close();}});
