import type {ComponentProps} from 'react';
export const custom0={className:"flex-1 scroll-fade overflow-y-auto p-4"};
export const custom1={className:"gap-2"};
export const custom2={className:"flex items-center gap-2"};
export const custom3={className:"h-[34px]"};
export const custom4={className:"sm:max-w-[425px]"};
export const custom5={className:"text-left"};
export const custom6={className:"px-4"};
export const custom7={className:"pt-2"};
export const custom8={className:"grid gap-3"};
export const custom9={className:"flex-1 p-4"};
export const custom10={className:"bg-muted group-data-[swipe-axis=x]/drawer-popup:size-full group-data-[swipe-axis=y]/drawer-popup:aspect-video group-data-[swipe-axis=y]/drawer-popup:w-full"};
export const custom11={className:"rounded-2xl bg-muted group-data-[swipe-axis=x]/drawer-popup:size-full group-data-[swipe-axis=y]/drawer-popup:h-80 group-data-[swipe-axis=y]/drawer-popup:w-full"};
export const custom12={className:"size-full rounded-2xl bg-muted"};
export const custom13={className:"flex flex-wrap gap-2"};
export const custom14={className:"p-4"};
export const custom15={className:"h-80 w-full bg-muted"};
export const custom16={className:"h-80 w-full bg-blue-200"};
export const custom17={className:"capitalize"};
export const custom18={className:"bg-muted group-data-[swipe-axis=x]/drawer-popup:size-full group-data-[swipe-axis=y]/drawer-popup:h-80 group-data-[swipe-axis=y]/drawer-popup:w-full"};
export const custom19={className:"data-[swipe-direction=down]:h-64"};
export const custom20={className:"flex-1 scroll-fade scrollbar-thin overflow-y-auto p-4"};
export const custom21={className:"mb-4 leading-normal style-lyra:mb-2 style-lyra:leading-relaxed"};
export const custom22={className:"data-[swipe-direction=up]:h-[50vh]"};
export const custom23={className:"data-[swipe-direction=left]:w-xl"};
export const custom24={className:"data-[swipe-direction=right]:w-xs"};
export const custom25={className:"max-h-[calc(100dvh-1rem)]"};
export const custom26={className:"grid flex-1 scroll-fade gap-3 overflow-y-auto p-4"};
export const custom27={className:"h-12 bg-muted"};
export function profileFormProps(props:ComponentProps<'form'>){return {...props,className:['grid items-start gap-6',props.className].filter(Boolean).join(' ')};}
