const classes={
  "alertLayout": "grid w-full max-w-md items-start gap-4",
  "landscape": "w-full max-w-sm rounded-lg bg-muted",
  "photo": "rounded-lg object-cover grayscale dark:brightness-20",
  "square": "w-full max-w-[12rem] rounded-lg bg-muted",
  "portrait": "w-full max-w-[10rem] rounded-lg bg-muted",
  "full": "w-full max-w-sm",
  "mutedFrame": "rounded-lg bg-muted",
  "caption": "mt-2 text-center text-sm text-muted-foreground",
  "badgeRow": "flex flex-wrap gap-2",
  "badgeCenter": "flex w-full flex-wrap justify-center gap-2",
  "buttons": "flex flex-wrap items-center gap-2 md:flex-row",
  "buttonSizes": "flex flex-col items-start gap-8 sm:flex-row",
  "buttonSizeRow": "flex items-start gap-2",
  "row": "flex gap-2",
  "rounded": "rounded-full",
  "rtlArrow": "rtl:rotate-180",
  "avatar": "size-12",
  "grayscale": "grayscale",
  "searchWidth": "sm:w-3/4",
  "emptyButtons": "flex-row justify-center gap-2",
  "muted": "text-muted-foreground",
  "rtlLink": "rtl:rotate-270",
  "maximum": "max-w-sm",
  "autoHeight": "h-auto",
  "code": "font-mono text-sm",
  "mono": "font-mono",
  "end": "ml-auto",
  "screenReader": "sr-only",
  "inputGroups": "grid w-full max-w-sm gap-6",
  "roundGroup": "[--radius:9999px]",
  "popover": "flex flex-col gap-1 rounded-xl text-sm",
  "medium": "font-medium",
  "prefix": "pl-1.5 text-muted-foreground",
  "favorite": "data-[favorite=true]:fill-blue-600 data-[favorite=true]:stroke-blue-600",
  "inputStack": "grid w-full max-w-sm gap-4",
  "dropdown": "pr-1.5! text-xs",
  "smallIcon": "size-3",
  "spin": "animate-spin",
  "narrow": "max-w-xs",
  "logicalEnd": "ms-auto",
  "inputGrid": "grid max-w-sm grid-cols-2",
  "required": "text-destructive",
  "formRow": "grid grid-cols-2 gap-4",
  "keys": "flex flex-col items-center gap-4",
  "keyInputs": "flex w-full max-w-xs flex-col gap-6",
  "separator": "flex max-w-sm flex-col gap-4 text-sm",
  "description": "flex flex-col gap-1.5",
  "heading": "leading-none font-medium",
  "skeleton": "flex items-center gap-4",
  "circle": "h-12 w-12 rounded-full",
  "lines": "space-y-2",
  "line250": "h-4 w-[250px]",
  "line200": "h-4 w-[200px]",
  "payment": "flex w-full max-w-xs flex-col gap-4 [--radius:1rem]",
  "clamp": "line-clamp-1",
  "paymentEnd": "flex-none justify-end",
  "amount": "text-sm tabular-nums",
  "textarea": "w-full max-w-xs",
  "tooltips": "grid gap-4",
  "tooltipRow": "flex flex-wrap justify-center gap-2"
};
export const demoStyle=(name:keyof typeof classes)=>({className:classes[name]});
export const demoProps=demoStyle;
