import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell, TableFooter, TableCaption } from '@table';
import { Checkbox } from '@checkbox';
import * as stylex from '@stylexjs/stylex';
const styles = stylex.create({ custom: { minWidth: 160 }, dynamic: (width: number) => ({ width }) });
export default function TableInstallFixture() {
  return <><DataTableInstallComposition/><TableSelectInstallComposition/><Table aria-label="Installed table" selectionMode="multiple" xstyle={styles.dynamic(320)} style={{ width: 300 }}><TableHeader><TableHead><Checkbox slot="selection" /></TableHead><TableHead isRowHeader>Name</TableHead></TableHeader><TableBody><TableRow><TableCell><Checkbox slot="selection" /></TableCell><TableCell style={{ fontWeight: 500 }} xstyle={styles.custom}>Row</TableCell></TableRow></TableBody><TableFooter><TableRow><TableCell>Total</TableCell></TableRow></TableFooter></Table><TableCaption>Installed caption</TableCaption></>;
}

import {useState} from 'react';
import {Button} from '@button';
import {Input} from '@input';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuGroup,DropdownMenuItem} from '@dropdown-menu';
import {createColumnHelper,columnFilteringFeature,columnVisibilityFeature,rowSortingFeature,rowSelectionFeature,rowPaginationFeature,createFilteredRowModel,createSortedRowModel,createPaginatedRowModel,filterFn_includesString,sortFn_text,tableFeatures,useTable,type SortingState,type ColumnFiltersState,type ColumnVisibilityState} from '@tanstack/react-table';
const features=tableFeatures({columnFilteringFeature,columnVisibilityFeature,rowSortingFeature,rowSelectionFeature,rowPaginationFeature,filteredRowModel:createFilteredRowModel(),sortedRowModel:createSortedRowModel(),paginatedRowModel:createPaginatedRowModel(),filterFns:{includesString:filterFn_includesString},sortFns:{text:sortFn_text}});
const helper=createColumnHelper<typeof features,{email:string}>();
const columns=helper.columns([helper.display({id:'select',header:()=> <Checkbox slot="selection"/>,cell:()=> <Checkbox slot="selection"/>,enableSorting:false,enableHiding:false}),helper.accessor('email',{header:'Email'})]);
const payments=[{email:'a@example.com'},{email:'b@example.com'},{email:'c@example.com'}];
function DataTableInstallComposition(){const[sorting,setSorting]=useState<SortingState>([]);const[columnFilters,setColumnFilters]=useState<ColumnFiltersState>([]);const[columnVisibility,setColumnVisibility]=useState<ColumnVisibilityState>({});const[rowSelection,setRowSelection]=useState({});const table=useTable({features,data:payments,columns,onSortingChange:setSorting,onColumnFiltersChange:setColumnFilters,onColumnVisibilityChange:setColumnVisibility,onRowSelectionChange:setRowSelection,initialState:{pagination:{pageSize:2,pageIndex:0}},state:{sorting,columnFilters,columnVisibility,rowSelection}});return <><Input aria-label="Filter installed payments" value={(table.getColumn('email')?.getFilterValue() as string)??''} onChange={event=>table.getColumn('email')?.setFilterValue(event.target.value)}/><DropdownMenuTrigger><Button>Columns</Button><DropdownMenu><DropdownMenuGroup selectionMode="multiple" selectedKeys={table.getVisibleFlatColumns().filter(column=>column.getCanHide()).map(column=>column.id)} onSelectionChange={keys=>table.setColumnVisibility(Object.fromEntries(table.getAllFlatColumns().map(column=>[column.id,!column.getCanHide()||keys==='all'||keys.has(column.id)])))}>{table.getAllColumns().filter(column=>column.getCanHide()).map(column=><DropdownMenuItem key={column.id} id={column.id}>{column.id}</DropdownMenuItem>)}</DropdownMenuGroup></DropdownMenu></DropdownMenuTrigger><Table aria-label="Installed TanStack payments" selectionMode="multiple" selectedKeys={table.getSelectedRowModel().rows.map(row=>row.id)} onSelectionChange={keys=>keys==='all'?table.toggleAllRowsSelected():table.setRowSelection(Object.fromEntries([...keys].map(key=>[key,true])))} sortDescriptor={sorting.length?{column:sorting[0].id,direction:sorting[0].desc?'descending':'ascending'}:undefined} onSortChange={sort=>table.setSorting([{id:String(sort.column),desc:sort.direction==='descending'}])}><TableHeader>{table.getFlatHeaders().map(header=><TableHead key={header.id} id={header.id} isRowHeader={header.index===1} allowsSorting={header.column.getCanSort()}><table.FlexRender header={header}/></TableHead>)}</TableHeader><TableBody renderEmptyState={()=>'No results.'}>{table.getRowModel().rows.map(row=><TableRow key={row.id} id={row.id}>{row.getVisibleCells().map(cell=><TableCell key={cell.id}><table.FlexRender cell={cell}/></TableCell>)}</TableRow>)}</TableBody></Table><Button onPress={()=>table.previousPage()} isDisabled={!table.getCanPreviousPage()}>Previous</Button><Button onPress={()=>table.nextPage()} isDisabled={!table.getCanNextPage()}>Next</Button></>;}
import {Select,SelectTrigger,SelectValue,SelectContent,SelectGroup,SelectItem} from '@select';
function TableSelectInstallComposition(){return <Table aria-label="Installed assignee"><TableHeader><TableHead isRowHeader>Task</TableHead><TableHead>Assignee</TableHead></TableHeader><TableBody><TableRow><TableCell>Design homepage</TableCell><TableCell><Select defaultValue="sarah"><SelectTrigger size="sm" style={{width:160}}><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem id="sarah">Sarah Chen</SelectItem><SelectItem id="marcus">Marc Rodriguez</SelectItem></SelectGroup></SelectContent></Select></TableCell></TableRow></TableBody></Table>;}
