import type{Meta,StoryObj}from'@storybook/react-vite';
import {ModalContext} from 'react-aria-components';
import{AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogTrigger,AlertDialogFooter,AlertDialogCancel,AlertDialogAction}from'@alert-dialog';
import{Button}from'@button';
import DemoExample from './alert-dialog-examples/demo';
import{AlertDialogBasic}from'./alert-dialog-examples/basic';
import{AlertDialogSmall}from'./alert-dialog-examples/small';
import{AlertDialogWithMedia}from'./alert-dialog-examples/media';
import{AlertDialogSmallWithMedia}from'./alert-dialog-examples/small-media';
import{AlertDialogDestructive}from'./alert-dialog-examples/destructive';
import{AlertDialogRtl}from'./alert-dialog-examples/rtl';
import*as Registry from'./alert-dialog-examples/registry';
import{customized}from'@alert-dialog-customizations';
const meta={title:'Components/AlertDialog',component:AlertDialog,args:{children:null},tags:['parity','viewport-390'],decorators:[Story=><main id="parity-root"><Story/></main>]}satisfies Meta<typeof AlertDialog>;
export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <DemoExample/>};
export const Basic:Story={render:()=> <AlertDialogBasic/>};
export const Small:Story={render:()=> <AlertDialogSmall/>};
export const Media:Story={render:()=> <AlertDialogWithMedia/>};
export const SmallMedia:Story={render:()=> <AlertDialogSmallWithMedia/>};
export const Destructive:Story={render:()=> <AlertDialogDestructive/>};
export const Rtl:Story={render:()=> <AlertDialogRtl/>};
export const RegistryBasic:Story={render:()=> <Registry.AlertDialogBasic/>};
export const RegistrySmall:Story={render:()=> <Registry.AlertDialogSmall/>};
export const RegistryMedia:Story={render:()=> <Registry.AlertDialogWithMedia/>};
export const RegistrySmallMedia:Story={render:()=> <Registry.AlertDialogSmallWithMedia/>};
export const RegistryDestructive:Story={render:()=> <Registry.AlertDialogDestructive/>};
export const InDialog:Story={render:()=> <Registry.AlertDialogInDialog/>};
export const Usage:Story={render:()=> <AlertDialogTrigger><Button>Open</Button><AlertDialogContent data-parity-portal><AlertDialogTitle>Confirm action</AlertDialogTitle><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction>Continue</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialogTrigger>};
export const DefaultOpen:Story={render:()=> <AlertDialogTrigger defaultOpen><Button>Open</Button><AlertDialog data-parity-portal><AlertDialogTitle>Default open</AlertDialogTitle><AlertDialogDescription>Description <a href="#">link</a></AlertDialogDescription></AlertDialog></AlertDialogTrigger>};
export const Context:Story={render:()=> <ModalContext.Provider value={{isOpen:true}}><AlertDialog data-parity-portal size="sm"><AlertDialogTitle>Context open</AlertDialogTitle><AlertDialogDescription>Inherited state</AlertDialogDescription></AlertDialog></ModalContext.Provider>};
export const Customized:Story={render:()=> <AlertDialogTrigger><Button>Custom</Button><AlertDialog data-parity-portal {...customized}><AlertDialogTitle>Custom</AlertDialogTitle><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction style={({isPressed})=>({opacity:isPressed?.5:1})}>Continue</AlertDialogAction></AlertDialogFooter></AlertDialog></AlertDialogTrigger>};
