import type { Meta, StoryObj } from '@storybook/react-vite';
import { CheckCircle2Icon, InfoIcon, AlertCircleIcon, AlertTriangleIcon } from 'lucide-react';
import { Alert, AlertTitle, AlertDescription, AlertAction } from '@alert';
import { Button } from '@button';
import { colors, customized, customTitle, customDescription } from '@alert-customizations';
const meta = { title: 'Components/Alert', component: Alert, tags: ['parity'], decorators: [Story => <main id="parity-root"><Story /></main>] } satisfies Meta<typeof Alert>;
export default meta;
type Story = StoryObj<typeof meta>;
const limit = { maxWidth: 448 };
export const Demo: Story = { render: () => <div style={{ display: 'grid', width: '100%', maxWidth: 448, alignItems: 'start', gap: 16 }}><Alert><CheckCircle2Icon /><AlertTitle>Payment successful</AlertTitle><AlertDescription>Your payment of $29.99 has been processed. A receipt has been sent to your email address.</AlertDescription></Alert><Alert><InfoIcon /><AlertTitle>New feature available</AlertTitle><AlertDescription>We've added dark mode support. You can enable it in your account settings.</AlertDescription></Alert></div> };
export const Basic: Story = { render: () => <Alert style={limit}><CheckCircle2Icon /><AlertTitle>Account updated successfully</AlertTitle><AlertDescription>Your profile information has been saved. Changes will be reflected immediately.</AlertDescription></Alert> };
export const Destructive: Story = { render: () => <Alert variant="destructive" style={limit}><AlertCircleIcon /><AlertTitle>Payment failed</AlertTitle><AlertDescription>Your payment could not be processed. Please check your payment method and try again.</AlertDescription></Alert> };
export const Action: Story = { render: () => <Alert style={limit}><AlertTitle>Dark mode is now available</AlertTitle><AlertDescription>Enable it under your profile settings to get started.</AlertDescription><AlertAction><Button size="xs">Enable</Button></AlertAction></Alert> };
export const Colors: Story = { render: () => <Alert style={limit} {...colors}><AlertTriangleIcon /><AlertTitle>Your subscription will expire in 3 days.</AlertTitle><AlertDescription>Renew now to avoid service interruption or upgrade to a paid plan to continue using the service.</AlertDescription></Alert> };
export const Rtl: Story = { render: () => <div dir="rtl" style={{ display: 'grid', width: '100%', maxWidth: 448, alignItems: 'start', gap: 16 }}><Alert><CheckCircle2Icon /><AlertTitle>تم الدفع بنجاح</AlertTitle><AlertDescription>تمت معالجة دفعتك البالغة 29.99 دولارًا. تم إرسال إيصال إلى عنوان بريدك الإلكتروني.</AlertDescription></Alert><Alert><InfoIcon /><AlertTitle>ميزة جديدة متاحة</AlertTitle><AlertDescription>لقد أضفنا دعم الوضع الداكن. يمكنك تفعيله في إعدادات حسابك.</AlertDescription></Alert></div> };
export const Content: Story = { tags: ['viewport-390'], render: () => <div style={{ display: 'grid', gap: 16 }}><Alert id="content-alert" style={limit}><InfoIcon /><AlertTitle>A <a href="#details">linked title</a></AlertTitle><AlertDescription><p>First paragraph with a <a href="#details">documentation link</a>.</p><p>Second paragraph with long text to verify responsive text wrapping for smaller viewports.</p></AlertDescription><AlertAction><Button size="xs" variant="outline">Read</Button></AlertAction></Alert><Alert variant={null}><AlertDescription>No variant or title</AlertDescription></Alert></div> };
export const Customized: Story = { render: () => <Alert variant="destructive" {...customized}><InfoIcon /><AlertTitle {...customTitle}>Custom styles</AlertTitle><AlertDescription {...customDescription}>StyleX and inline overrides</AlertDescription><AlertAction style={{ top: 4, right: 4 }}>!</AlertAction></Alert> };

export const RtlAction: Story = { render: () => <div dir="rtl"><Alert style={limit}><InfoIcon /><AlertTitle>ميزة جديدة متاحة</AlertTitle><AlertDescription>يمكنك تفعيل الوضع الداكن في إعدادات حسابك.</AlertDescription><AlertAction><Button size="xs">تفعيل</Button></AlertAction></Alert></div> };
