import {useState,type CSSProperties} from 'react';
import {Attachment,AttachmentMedia,AttachmentContent,AttachmentTitle,AttachmentDescription,AttachmentActions,AttachmentAction,AttachmentTrigger} from '@attachment';
import {FileTextIcon} from 'lucide-react';
import {attachmentCustom} from '@attachment-customizations';
export function AttachmentConditions(){const [gap,setGap]=useState(8);const [count,setCount]=useState(0);return <div style={{display:'flex',flexDirection:'column',gap:20}}><button onClick={()=>setGap(18)}>Change gap</button><Attachment {...attachmentCustom(gap)} style={{'--attachment-gap':`${gap}px`,'--attachment-width':'22rem',gap:12} as CSSProperties}><AttachmentMedia><FileTextIcon/></AttachmentMedia><AttachmentContent><AttachmentTitle>Customized file</AttachmentTitle><AttachmentDescription>Native style wins</AttachmentDescription></AttachmentContent><AttachmentActions><AttachmentAction onPress={()=>setCount(n=>n+1)}>Action {count}</AttachmentAction></AttachmentActions><AttachmentTrigger onClick={()=>setCount(n=>n+10)} aria-label="Preview customized file"/></Attachment><Attachment size={null} orientation={null}><AttachmentMedia variant={null}><FileTextIcon/></AttachmentMedia><AttachmentContent><AttachmentTitle>Null variants</AttachmentTitle></AttachmentContent></Attachment><Attachment state="uploading"><Attachment state="done"><AttachmentTitle>Nested uploading title</AttachmentTitle></Attachment></Attachment></div>;}
import {Dialog,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from '@dialog';
export function AttachmentControlledDialog(){const [open,setOpen]=useState(false);return <DialogTrigger isOpen={open} onOpenChange={setOpen}><Attachment><AttachmentMedia><FileTextIcon/></AttachmentMedia><AttachmentContent><AttachmentTitle>Controlled preview.pdf</AttachmentTitle></AttachmentContent><AttachmentActions><AttachmentAction onPress={()=>{}}>Copy preview link</AttachmentAction></AttachmentActions><AttachmentTrigger onClick={()=>setOpen(true)} aria-label="Open controlled preview"/></Attachment><Dialog><DialogHeader><DialogTitle>Controlled preview.pdf</DialogTitle><DialogDescription>Explicit native onClick controls the actual dialog.</DialogDescription></DialogHeader></Dialog></DialogTrigger>;}
import {Spinner} from '@spinner';
export function AttachmentMatrix(){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:20}}>{(['default','sm','xs'] as const).flatMap(size=>(['horizontal','vertical'] as const).flatMap(orientation=>(['idle','uploading','processing','error','done'] as const).map(state=><div key={`${size}-${orientation}-${state}`}><p>{size} / {orientation} / {state}</p><Attachment size={size} orientation={orientation} state={state}><AttachmentMedia>{state==='uploading'?<Spinner/>:<FileTextIcon/>}</AttachmentMedia><AttachmentContent><AttachmentTitle>matrix.pdf</AttachmentTitle><AttachmentDescription>PDF · 2.4 MB</AttachmentDescription></AttachmentContent><AttachmentActions><AttachmentAction aria-label="Remove matrix file">×</AttachmentAction></AttachmentActions></Attachment></div>)))}</div>;}
