import type {Meta,StoryObj} from '@storybook/react-vite';
import {I18nProvider} from 'react-aria-components';
import {AttachmentDemo} from './attachment-examples/demo';
import {AttachmentImage} from './attachment-examples/image';
import {AttachmentStates} from './attachment-examples/states';
import {AttachmentSizes} from './attachment-examples/sizes';
import {AttachmentGroupDemo} from './attachment-examples/group';
import {AttachmentTriggerDemo} from './attachment-examples/trigger';
import * as Registry from './attachment-examples/registry';
const meta={title:'Components/Attachment',id:'components-attachment',tags:['parity','viewport-390'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta;export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <AttachmentDemo/>};export const Image:Story={render:()=> <AttachmentImage/>};export const States:Story={render:()=> <AttachmentStates/>};export const Sizes:Story={render:()=> <AttachmentSizes/>};export const Group:Story={render:()=> <AttachmentGroupDemo/>};export const Trigger:Story={render:()=> <AttachmentTriggerDemo/>};
export const RegistryFiles:Story={render:()=> <Registry.AttachmentFiles/>};export const RegistryContentOnly:Story={render:()=> <Registry.AttachmentContentOnly/>};export const RegistryStates:Story={render:()=> <Registry.AttachmentStates/>};export const RegistryImages:Story={render:()=> <Registry.AttachmentImages/>};export const RegistryImageStates:Story={render:()=> <Registry.AttachmentImageStates/>};export const RegistrySizes:Story={render:()=> <Registry.AttachmentSizes/>};export const RegistryScrollableGroup:Story={render:()=> <Registry.AttachmentScrollableGroup/>};export const RegistryTriggers:Story={render:()=> <Registry.AttachmentTriggers/>};
export const Rtl:Story={render:()=> <I18nProvider locale="ar"><div dir="rtl"><AttachmentDemo/><AttachmentImage/><AttachmentStates/><AttachmentGroupDemo/><AttachmentTriggerDemo/></div></I18nProvider>};
import {AttachmentConditions} from './attachment-conditions';
export const Conditions:Story={render:()=> <AttachmentConditions/>};
import {AttachmentControlledDialog} from './attachment-conditions';
export const ControlledDialog:Story={render:()=> <AttachmentControlledDialog/>};
import {AttachmentMatrix} from './attachment-conditions';
export const Matrix:Story={render:()=> <AttachmentMatrix/>};
export const MatrixRtl:Story={render:()=> <I18nProvider locale="ar"><div dir="rtl"><AttachmentMatrix/></div></I18nProvider>};
