import {useState,type CSSProperties} from 'react';
import type {Meta,StoryObj} from '@storybook/react-vite';
import {Bubble,BubbleContent,BubbleGroup,BubbleReactions} from '@bubble';
import {bubbleCustom} from '@bubble-customizations';
import * as Registry from './bubble-examples/registry';
import {BubbleDemo} from './bubble-examples/demo';
import {BubbleVariantsDemo} from './bubble-examples/variants';
import {BubbleAlignmentDemo} from './bubble-examples/alignment';
import {BubbleGroupDemo} from './bubble-examples/group-demo';
import {BubbleLinkButtonDemo} from './bubble-examples/link-button';
import {BubbleReactionsDemo} from './bubble-examples/reactions';
import {BubbleCollapsible} from './bubble-examples/collapsible';
import {BubbleTooltipDemo} from './bubble-examples/tooltip';
import {BubblePopoverDemo} from './bubble-examples/popover';
const meta={title:'Components/Bubble',component:Bubble,tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Bubble>;
export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <BubbleDemo/>};
export const Variants:Story={render:()=> <BubbleVariantsDemo/>};
export const Alignment:Story={render:()=> <BubbleAlignmentDemo/>};
export const GroupDemo:Story={render:()=> <BubbleGroupDemo/>};
export const LinkButton:Story={render:()=> <BubbleLinkButtonDemo/>};
export const Reactions:Story={render:()=> <BubbleReactionsDemo/>};
export const Collapsible:Story={render:()=> <BubbleCollapsible/>};
export const Tooltip:Story={render:()=> <BubbleTooltipDemo/>};
export const Popover:Story={render:()=> <BubblePopoverDemo/>};
export const RegistryVariants:Story={render:()=> <Registry.BubbleVariants/>};
export const RegistrySizes:Story={render:()=> <Registry.BubbleSizes/>};
export const RegistryGrouped:Story={render:()=> <Registry.BubbleGrouped/>};
export const RegistryCollapsible:Story={render:()=> <Registry.BubbleCollapsible/>};
export const RegistryWithReactions:Story={render:()=> <Registry.BubbleWithReactions/>};
export const RegistryReactionsButtons:Story={render:()=> <Registry.BubbleReactionsButtons/>};
export const RegistryAlignment:Story={render:()=> <Registry.BubbleAlignment/>};
export const RegistryButtonLinks:Story={render:()=> <Registry.BubbleButtonLinks/>};
export const Usage:Story={render:()=> <Bubble><BubbleContent>Checked the registry.</BubbleContent><BubbleReactions role="img" aria-label="Thumbs up">👍</BubbleReactions></Bubble>};
export const Rtl:Story={render:()=> <div dir="rtl"><BubbleDemo/><Registry.BubbleWithReactions/></div>};
const variants=['default','secondary','muted','tinted','outline','ghost','destructive'] as const;
export const InteractiveVariants:Story={render:()=> <BubbleGroup>{variants.map(variant=><Bubble key={variant} variant={variant}><BubbleContent render={props=><button {...props} type="button"/>}>{variant}</BubbleContent></Bubble>)}</BubbleGroup>};
function Custom(){const[gap,setGap]=useState(8);return <><button onClick={()=>setGap(16)}>Change gap</button><Bubble><BubbleContent {...bubbleCustom(gap)} style={{'--bubble-gap':gap+'px',padding:12} as CSSProperties}>Override</BubbleContent></Bubble></>;}
export const Customization:Story={render:()=> <Custom/>};
export const Nested:Story={render:()=> <Bubble variant="ghost"><BubbleContent>Outer ghost<Bubble><BubbleContent>Inner default</BubbleContent></Bubble></BubbleContent><div><BubbleContent>Indirect child</BubbleContent></div></Bubble>};
