import {useState,type CSSProperties} from 'react';
import type {Meta,StoryObj} from '@storybook/react-vite';
import {ButtonGroup,ButtonGroupText,ButtonGroupSeparator,buttonGroupProps} from '@button-group';
import {Button,buttonProps} from '@button';
import {Input} from '@input';
import {InputGroup,InputGroupAddon,InputGroupButton,InputGroupInput} from '@input-group';
import {Tooltip,TooltipTrigger} from '@tooltip';
import {Focusable,ButtonContext,SeparatorContext} from 'react-aria-components';
import {PlusIcon,MinusIcon,FlipHorizontalIcon,FlipVerticalIcon,RotateCwIcon,SearchIcon,AudioLinesIcon,HeartIcon,ArrowLeftIcon,ArrowRightIcon,CopyIcon,ShareIcon,TrashIcon} from 'lucide-react';
import {IconPlus} from '@tabler/icons-react';
import {voice,dynamic} from '@button-group-customizations';
const meta={title:'Components/ButtonGroup',component:ButtonGroup,tags:['parity'],decorators:[Story=><main id="parity-root" style={{display:'grid',gap:16,width:620}}><Story/></main>]} satisfies Meta<typeof ButtonGroup>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Usage:Story={render:()=> <ButtonGroup aria-label="Button group"><Button>Button 1</Button><Button>Button 2</Button></ButtonGroup>};
export const Orientation:Story={render:()=> <ButtonGroup orientation="vertical" aria-label="Media controls" style={{height:'fit-content'}}><Button variant="outline" size="icon"><PlusIcon/></Button><Button variant="outline" size="icon"><MinusIcon/></Button></ButtonGroup>};
export const Size:Story={render:()=> <div style={{display:'flex',flexDirection:'column',alignItems:'flex-start',gap:32}}>{(['sm','default','lg'] as const).map((size,i)=><ButtonGroup key={size}><Button variant="outline" size={size}>{['Small','Default','Large'][i]}</Button><Button variant="outline" size={size}>Button</Button><Button variant="outline" size={size}>Group</Button><Button variant="outline" size={(['icon-sm','icon','icon-lg'] as const)[i]}><PlusIcon/></Button></ButtonGroup>)}</div>};
export const Nested:Story={render:()=> <ButtonGroup><ButtonGroup><Button variant="outline" size="icon"><PlusIcon/></Button></ButtonGroup><ButtonGroup><InputGroup><InputGroupInput placeholder="Send a message..."/><TooltipTrigger><InputGroupAddon align="inline-end"><AudioLinesIcon/></InputGroupAddon><Tooltip data-parity-portal>Voice Mode</Tooltip></TooltipTrigger></InputGroup></ButtonGroup></ButtonGroup>};
export const Separator:Story={render:()=> <ButtonGroup><Button variant="secondary" size="sm">Copy</Button><ButtonGroupSeparator/><Button variant="secondary" size="sm">Paste</Button></ButtonGroup>};
export const Split:Story={render:()=> <ButtonGroup><Button variant="secondary">Button</Button><ButtonGroupSeparator/><Button size="icon" variant="secondary"><IconPlus/></Button></ButtonGroup>};
export const InInput:Story={render:()=> <ButtonGroup><Input placeholder="Search..."/><Button variant="outline" aria-label="Search"><SearchIcon/></Button></ButtonGroup>};
function VoiceGroup(){const[enabled,setEnabled]=useState(false);return <ButtonGroup style={{'--radius':'9999rem'} as CSSProperties}><ButtonGroup><Button variant="outline" size="icon"><PlusIcon/></Button></ButtonGroup><ButtonGroup><InputGroup><InputGroupInput placeholder={enabled?'Record and send audio...':'Send a message...'} disabled={enabled}/><InputGroupAddon align="inline-end"><TooltipTrigger><InputGroupButton onClick={()=>setEnabled(!enabled)} size="icon-xs" data-active={enabled} {...voice} aria-label="Voice Mode" aria-pressed={enabled}><AudioLinesIcon/></InputGroupButton><Tooltip data-parity-portal>Voice Mode</Tooltip></TooltipTrigger></InputGroupAddon></InputGroup></ButtonGroup></ButtonGroup>}
export const InInputGroup:Story={render:()=> <VoiceGroup/>};
export const Text:Story={render:()=> <><ButtonGroup><ButtonGroupText>Text</ButtonGroupText><Button variant="outline">Another Button</Button></ButtonGroup><ButtonGroup><ButtonGroupText render={props=><label {...props} htmlFor="input-text"/>}>GPU Size</ButtonGroupText><Input id="input-text" placeholder="Type something here..."/></ButtonGroup></>};
export const Variants:Story={render:()=> <>{(['default','outline','secondary','ghost','destructive','link'] as const).map(variant=><ButtonGroup key={variant} aria-label={variant}><Button variant={variant}>First</Button><ButtonGroupSeparator/><Button variant={variant}>Second</Button><Button variant={variant} isDisabled>Disabled</Button></ButtonGroup>)}</>};
export const Edges:Story={render:()=> <><ButtonGroup orientation={null}><Button variant="outline">No orientation</Button><Button variant="outline">Second</Button></ButtonGroup><ButtonGroup data-slot="custom-group" data-orientation="vertical"><Button variant="outline">DOM override</Button><Button variant="outline">Horizontal styles</Button></ButtonGroup><ButtonGroup orientation="vertical"><Button variant="secondary">First</Button><ButtonGroupSeparator orientation="horizontal"/><Button variant="secondary">Last</Button></ButtonGroup><ButtonGroup><ButtonGroupText data-slot="custom-text"><SearchIcon className="size-explicit" style={{width:22,height:22}}/></ButtonGroupText><span>No slot</span><Button variant="outline">Last slot</Button><span>Trailing span</span></ButtonGroup></>};
export const NestedVertical:Story={render:()=> <ButtonGroup orientation="vertical" aria-label="Design tools palette"><ButtonGroup orientation="vertical">{[SearchIcon,CopyIcon,ShareIcon].map((Icon,i)=><Button variant="outline" size="icon" key={i}><Icon/></Button>)}</ButtonGroup><ButtonGroup orientation="vertical">{[FlipHorizontalIcon,FlipVerticalIcon,RotateCwIcon].map((Icon,i)=><Button variant="outline" size="icon" key={i}><Icon/></Button>)}</ButtonGroup><ButtonGroup><Button variant="outline" size="icon"><TrashIcon/></Button></ButtonGroup></ButtonGroup>};
export const Like:Story={render:()=> <ButtonGroup><Button variant="outline"><HeartIcon data-icon="inline-start"/> Like</Button><span data-slot="button" {...buttonProps({variant:'outline',size:'icon',style:{width:48}})}>1.2K</span></ButtonGroup>};
export const Pagination:Story={render:()=> <ButtonGroup><Button variant="outline" size="sm"><ArrowLeftIcon data-icon="inline-start"/>Previous</Button>{[1,2,3,4,5].map(n=><Button variant="outline" size="sm" key={n}>{n}</Button>)}<Button variant="outline" size="sm">Next<ArrowRightIcon data-icon="inline-end"/></Button></ButtonGroup>};
export const PaginationSplit:Story={render:()=> <ButtonGroup><ButtonGroup>{[1,2,3,4,5].map(n=><Button variant="outline" size="sm" key={n}>{n}</Button>)}</ButtonGroup><ButtonGroup><Button variant="outline" size="icon-xs"><ArrowLeftIcon/></Button><Button variant="outline" size="icon-xs"><ArrowRightIcon/></Button></ButtonGroup></ButtonGroup>};
export const Navigation:Story={render:()=> <ButtonGroup><ButtonGroup><Button variant="outline"><ArrowLeftIcon/></Button><Button variant="outline"><ArrowRightIcon/></Button></ButtonGroup><ButtonGroup aria-label="Single navigation button"><Button variant="outline" size="icon"><ArrowLeftIcon/></Button></ButtonGroup></ButtonGroup>};
export const ShowcaseNested:Story={render:()=> <ButtonGroup><ButtonGroup><Button variant="outline" size="icon"><PlusIcon/></Button></ButtonGroup><ButtonGroup><InputGroup><InputGroupInput placeholder="Send a message..."/><TooltipTrigger><Focusable><InputGroupAddon align="inline-end" role="button"><AudioLinesIcon/></InputGroupAddon></Focusable><Tooltip data-parity-portal>Voice Mode</Tooltip></TooltipTrigger></InputGroup></ButtonGroup></ButtonGroup>};
function CustomizedGroup(){const[width,setWidth]=useState(260);return <><ButtonGroup {...dynamic(width)} style={{minWidth:280}} ref={node=>{if(node)node.dataset.ref='attached'}} onClick={()=>setWidth(320)} aria-label="Custom group"><Button variant="outline">Resize</Button><ButtonGroupText {...dynamic(70)} style={{width:80}}>Text</ButtonGroupText><ButtonGroupSeparator {...dynamic(10)} style={{width:12}}/></ButtonGroup><div role="group" data-slot="button-group" {...buttonGroupProps({orientation:'vertical',...dynamic(180),style:{minWidth:200}})}><Button variant="outline">Helper</Button><Button variant="outline">Second</Button></div></>}
export const Customized:Story={render:()=> <CustomizedGroup/>};
export const Basic:Story={render:()=> <ButtonGroup><Button variant="outline">Button</Button><Button variant="outline">Another Button</Button></ButtonGroup>};
export const WithInput:Story={render:()=> <><ButtonGroup><Button variant="outline">Button</Button><Input placeholder="Type something here..."/></ButtonGroup><ButtonGroup><Input placeholder="Type something here..."/><Button variant="outline">Button</Button></ButtonGroup></>};
export const Icons:Story={render:()=> <ButtonGroup>{[FlipHorizontalIcon,FlipVerticalIcon,RotateCwIcon].map((Icon,i)=><Button variant="outline" key={i}><Icon/></Button>)}</ButtonGroup>};
export const ShowcaseInputGroup:Story={render:()=> <InputGroup><InputGroupInput placeholder="Type to search..."/><InputGroupAddon align="inline-start"><SearchIcon/></InputGroupAddon></InputGroup>};

export const Context:Story={render:()=> <ButtonContext.Provider value={{isDisabled:true,style:({isDisabled})=>({opacity:isDisabled?0.4:1})}}><ButtonGroup><Button>Inherited disabled</Button><Button isDisabled={false}>Enabled override</Button><SeparatorContext.Provider value={{orientation:'horizontal'}}><ButtonGroupSeparator/><ButtonGroupSeparator orientation="horizontal" data-orientation="horizontal"/></SeparatorContext.Provider></ButtonGroup></ButtonContext.Provider>};
export const Typography:Story={render:()=> <ButtonGroup style={{fontSize:20}}><ButtonGroupText style={{fontSize:20}}>Large text</ButtonGroupText><Button variant="outline" style={{fontSize:20}}>Large button</Button></ButtonGroup>};

export const TextIcons:Story={render:()=> <ButtonGroup><ButtonGroupText><SearchIcon/>Text</ButtonGroupText><ButtonGroupText><SearchIcon className="size-explicit" style={{width:22,height:22}}/>Explicit</ButtonGroupText></ButtonGroup>};
