import{ChartAnimationControl}from'./chart-animation';
import type{Meta,StoryObj}from'@storybook/react-vite';
import{I18nProvider}from'react-aria-components';
import{ChartDemo}from'./chart-examples/chart-demo';
import{ChartExample}from'./chart-examples/chart-example';
import{ChartBarDemoGrid}from'./chart-examples/chart-example-grid';
import{ChartBarDemoAxis}from'./chart-examples/chart-example-axis';
import{ChartBarDemoTooltip}from'./chart-examples/chart-example-tooltip';
import{ChartBarDemoLegend}from'./chart-examples/chart-example-legend';
import{ChartTooltipDemo}from'./chart-examples/chart-tooltip';
import{ChartRtl}from'./chart-examples/chart-rtl';
const meta={title:'Components/Chart',tags:['parity','viewport-390'],decorators:[Story=><ChartAnimationControl><main id="parity-root"><Story/></main></ChartAnimationControl>]}satisfies Meta;export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <ChartDemo/>};export const Example:Story={render:()=> <ChartExample/>};export const Grid:Story={render:()=> <ChartBarDemoGrid/>};export const Axis:Story={render:()=> <ChartBarDemoAxis/>};export const Tooltip:Story={render:()=> <ChartBarDemoTooltip/>};export const Legend:Story={render:()=> <ChartBarDemoLegend/>};export const TooltipAnatomy:Story={render:()=> <ChartTooltipDemo/>};export const Rtl:Story={decorators: [Story => <I18nProvider locale="ar"><div dir="rtl"><Story /></div></I18nProvider>], parameters: { originalExample: "chart-rtl" }, render: () => <ChartRtl/>};
import{ChartApi}from'./chart-api';
export const Api:Story={render:()=> <ChartApi/>};
import{ChartNativeOverrides}from'./chart-api';
export const NativeOverrides:Story={tags:['!parity','!viewport-390'],render:()=> <ChartNativeOverrides/>};
import{ChartAreaExample,ChartBarExample,ChartLineExample,ChartPieExample,ChartRadialExample,ChartRadarExample}from'./chart-examples/registry';
export const RegistryArea:Story={render:()=> <ChartAreaExample/>};export const RegistryBar:Story={render:()=> <ChartBarExample/>};export const RegistryLine:Story={render:()=> <ChartLineExample/>};export const RegistryPie:Story={render:()=> <ChartPieExample/>};export const RegistryRadial:Story={render:()=> <ChartRadialExample/>};export const RegistryRadar:Story={render:()=> <ChartRadarExample/>};
