import {useState} from 'react';
import type {Meta,StoryObj} from '@storybook/react-vite';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem,CommandSeparator,CommandShortcut} from '@command';
import {commandDemo,commandCustom,commandItem} from '@command-customizations';
import {CommandDemo} from './command-examples/demo';
import {CommandBasic} from './command-examples/basic';
import {CommandWithShortcuts} from './command-examples/shortcuts';
import {CommandWithGroups} from './command-examples/groups';
import {CommandManyItems} from './command-examples/scrollable';
import {CommandRtl} from './command-examples/rtl';
import {CommandDialogDemo} from './command-examples/dialog';
import * as Registry from './command-examples/registry';
const meta={title:'Components/Command',component:Command,args:{children:null},tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Command>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <CommandDemo/>};
export const Basic:Story={render:()=> <CommandBasic/>};
export const Shortcuts:Story={render:()=> <CommandWithShortcuts/>};
export const Groups:Story={render:()=> <CommandWithGroups/>};
export const Scrollable:Story={render:()=> <CommandManyItems/>};
export const Rtl:Story={render:()=> <CommandRtl/>};
export const KeyboardDialog:Story={render:()=> <CommandDialogDemo/>};
export const RegistryInline:Story={render:()=> <Registry.CommandInline/>};
export const RegistryBasic:Story={render:()=> <Registry.CommandBasic/>};
export const RegistryShortcuts:Story={render:()=> <Registry.CommandWithShortcuts/>};
export const RegistryGroups:Story={render:()=> <Registry.CommandWithGroups/>};
export const RegistryScrollable:Story={render:()=> <Registry.CommandManyItems/>};
export const Usage:Story={render:()=> <Command {...commandDemo}><CommandInput placeholder="Type a command or search..."/><CommandList renderEmptyState={()=> <CommandEmpty>No results found.</CommandEmpty>}><CommandGroup heading="Suggestions">{['Calendar','Search Emoji','Calculator'].map(text=><CommandItem key={text}>{text}</CommandItem>)}</CommandGroup><CommandSeparator/><CommandGroup heading="Settings">{['Profile','Billing','Settings'].map(text=><CommandItem key={text}>{text}</CommandItem>)}</CommandGroup></CommandList></Command>};
function StateExample({disabled=false,invalid=false,custom=false}:{disabled?:boolean;invalid?:boolean;custom?:boolean}){const[value,setValue]=useState('');return <><Command {...(custom?commandCustom:commandDemo)} style={custom?{width:360}:undefined}><CommandInput placeholder="Search fruit" disabled={disabled} aria-invalid={invalid||undefined} style={custom?({isFocused})=>({fontWeight:isFocused?600:400}):undefined}/><CommandList selectionMode="single" onAction={key=>setValue(String(key))} renderEmptyState={()=> <CommandEmpty>Nothing found</CommandEmpty>}><CommandGroup heading="Fruit" items={[{id:'apple',name:'Apple'},{id:'pear',name:'Pear'},{id:'orange',name:'Orange'}]}>{item=><CommandItem id={item.id} textValue={item.name} isDisabled={item.id==='pear'} {...(custom?commandItem:{})}>{({isSelected})=><><span>{item.name}</span><CommandShortcut>{isSelected?'Selected':'⌘1'}</CommandShortcut></>}</CommandItem>}</CommandGroup></CommandList></Command><output aria-label="Action">{value}</output></>;}
export const Selection:Story={render:()=> <StateExample/>};
export const DisabledInput:Story={render:()=> <StateExample disabled/>};
export const InvalidInput:Story={render:()=> <StateExample invalid/>};
export const Customization:Story={render:()=> <StateExample custom/>};
export const CustomFilter:Story={render:()=> <Command {...commandDemo} filter={(text,input)=>text.toLowerCase().startsWith(input.toLowerCase())}><CommandInput placeholder="Prefix search"/><CommandList items={[{id:'one',name:'Alpha'},{id:'two',name:'Beta'}]} renderEmptyState={()=> <CommandEmpty>Nothing found</CommandEmpty>}>{item=><CommandItem id={item.id}>{item.name}</CommandItem>}</CommandList></Command>};
