import './data-table.css';
import * as stylex from '@stylexjs/stylex';
import {buttonProps} from '@button';

const styles=stylex.create({capitalize:{textTransform:'capitalize'},lowercase:{textTransform:'lowercase'},right:{textAlign:'right'},start:{textAlign:'start'},medium:{fontWeight:500},srOnly:{position:'absolute',width:1,height:1,padding:0,margin:-1,overflow:'hidden',clipPath:'inset(50%)',whiteSpace:'nowrap',borderWidth:0},menu44:{width:'11rem'},menu40:{width:'10rem'},full:{width:'100%'},toolbar:{display:'flex',alignItems:'center',paddingBlock:'1rem'},gap:{gap:'.5rem'},filter:{maxWidth:'24rem'},left:{marginLeft:'auto'},startMargin:{marginInlineStart:'auto'},frame:{overflow:'hidden',borderRadius:'calc(var(--radius) * .8)',borderWidth:1,borderStyle:'solid'},footer:{display:'flex',alignItems:'center',justifyContent:'flex-end',paddingBlock:'1rem'},count:{flex:'1 1 0%',fontSize:'.875rem',lineHeight:'calc(1.25 / .875)',color:'var(--muted-foreground)'},pagination:{display:'flex',gap:'.5rem'}});
function presentation(...styles:stylex.StyleXStyles[]){const {className,style}=stylex.props(...styles);return {className,style};}
export const ghostHeader=buttonProps({variant:'ghost'});
export const capitalize=presentation(styles.capitalize),lowercase=presentation(styles.lowercase),amountRight=presentation(styles.right),valueRight=presentation(styles.right,styles.medium),amountStart=presentation(styles.start),valueStart=presentation(styles.start,styles.medium),srOnly=presentation(styles.srOnly),menu44={xstyle:styles.menu44},menu40={xstyle:styles.menu40},full=presentation(styles.full),toolbar=presentation(styles.toolbar),toolbarGap=presentation(styles.toolbar,styles.gap),filterInput={xstyle:styles.filter},marginLeft={xstyle:styles.left},marginStart={xstyle:styles.startMargin},frame=presentation(styles.frame),footerSpace={...presentation(styles.footer),className:presentation(styles.footer).className+' ariax-data-space'},footerGap=presentation(styles.footer,styles.gap),selectionCount=presentation(styles.count),paginationSpace={className:'ariax-data-space'},paginationGap=presentation(styles.pagination);

export const capitalizeItem={xstyle:styles.capitalize};
