import type{Meta,StoryObj}from '@storybook/react-vite';
import {Drawer,DrawerTrigger,DrawerContent,DrawerHeader,DrawerTitle,DrawerDescription,DrawerFooter,DrawerClose} from '@drawer';
import{Button}from '@button';
import*as Registry from './drawer-examples/registry';
import{DrawerDemo}from './drawer-examples/demo';
import{DrawerWithSides}from './drawer-examples/sides';
import{DrawerSwipeHandle}from './drawer-examples/swipe-handle';
import{DrawerNested}from './drawer-examples/nested';
import{DrawerNonModal}from './drawer-examples/non-modal';
import{DrawerSnapPoints}from './drawer-examples/snap-points';
import{DrawerDialogDemo}from './drawer-examples/dialog';
import{DrawerRtl}from './drawer-examples/rtl';
const meta={title:'Components/Drawer',component:Drawer,tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Drawer>;export default meta;type Story=StoryObj<typeof meta>;
export const DemoExample:Story={tags:['viewport-390'],render:()=> <DrawerDemo/>};
export const Sides:Story={tags:['viewport-390'],render:()=> <DrawerWithSides/>};
export const SwipeHandle:Story={render:()=> <DrawerSwipeHandle/>};
export const Nested:Story={render:()=> <DrawerNested/>};
export const NonModal:Story={render:()=> <DrawerNonModal/>};
export const SnapPoints:Story={tags:['viewport-390'],render:()=> <DrawerSnapPoints/>};
export const Dialog:Story={tags:['viewport-390'],render:()=> <DrawerDialogDemo/>};
export const Rtl:Story={tags:['viewport-390'],render:()=> <DrawerRtl/>};
export const RegistryDemo:Story={render:()=> <Registry.DrawerDemo/>};
export const RegistrySwipeHandle:Story={render:()=> <Registry.DrawerSwipeHandleExample/>};
export const RegistryCustomSize:Story={render:()=> <Registry.DrawerCustomWidthAndHeight/>};
export const RegistryPosition:Story={render:()=> <Registry.DrawerPosition/>};
export const RegistryScrollable:Story={render:()=> <Registry.DrawerScrollable/>};
export const RegistrySnapPoints:Story={render:()=> <Registry.DrawerSnapPoints/>};
export const RegistryNested:Story={render:()=> <Registry.DrawerNested/>};
export const RegistryNonModal:Story={render:()=> <Registry.DrawerNonModal/>};
export const Usage:Story={render:()=> <Drawer><DrawerTrigger render={<Button/>}>Open</DrawerTrigger><DrawerContent><DrawerHeader><DrawerTitle>Are you absolutely sure?</DrawerTitle><DrawerDescription>This action cannot be undone.</DrawerDescription></DrawerHeader><DrawerFooter><Button>Submit</Button><DrawerClose render={<Button variant="outline"/>}>Cancel</DrawerClose></DrawerFooter></DrawerContent></Drawer>};
import{callbackTrigger,callbackPopup}from'@drawer-customizations';
export const Callback:Story={render:()=> <Drawer><DrawerTrigger render={<Button/>} {...callbackTrigger} style={({open})=>({width:open?220:200,opacity:.9})}>Callback open</DrawerTrigger><DrawerContent {...callbackPopup} style={({open})=>({width:open?300:250,fontSize:20})}><DrawerHeader><DrawerTitle>Callback</DrawerTitle><DrawerDescription>Native style wins</DrawerDescription></DrawerHeader><DrawerFooter><DrawerClose render={<Button/>} {...callbackTrigger} style={({disabled})=>({width:disabled?190:210})}>Callback close</DrawerClose></DrawerFooter></DrawerContent></Drawer>};
