import type {CSSProperties} from 'react';
import * as stylex from '@stylexjs/stylex';
const styles=stylex.create({w32:{width:'8rem'},w36:{width:'9rem'},w40:{width:'10rem'},w44:{width:'11rem'},w48:{width:'12rem'},min56:{minWidth:'14rem'},size8:{width:'2rem',height:'2rem'},right:{textAlign:'right'},medium:{fontWeight:500},sr:{position:'absolute',width:1,height:1,padding:0,margin:-1,overflow:'hidden',clipPath:'inset(50%)',whiteSpace:'nowrap',borderWidth:0},dynamic:(width:number)=>({width})});
const map={'w-32':styles.w32,'w-36':styles.w36,'w-40':styles.w40,'w-44':styles.w44,'w-48':styles.w48,'min-w-56':styles.min56,'size-8':styles.size8,'text-right':styles.right,'font-medium':styles.medium};
export function dropdownCustom(key:keyof typeof map){return {xstyle:map[key]};}
export function dropdownDynamic(width:number){return {xstyle:[styles.w32,styles.dynamic(width)],style:undefined as CSSProperties|undefined};}
export function dropdownSr(){const sx=stylex.props(styles.sr);return {className:sx.className,style:sx.style};}
const registryStyles=stylex.create({fit:{width:'fit-content'},wrap:{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:'.5rem'},capitalize:{textTransform:'capitalize'},min40:{minWidth:'10rem'},min56:{minWidth:'14rem'},row:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'1rem'},account:{height:'3rem',justifyContent:'flex-start',paddingInline:'.5rem',paddingInlineStart:'.5rem',paddingInlineEnd:'.5rem',maxWidth:{default:null,'@media (min-width: 48rem)':'200px'}},round:{borderRadius:'var(--radius)'},details:{display:'grid',flex:1,textAlign:'left',fontSize:'.875rem',lineHeight:1.25},truncate:{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'},semibold:{fontWeight:600},description:{fontSize:'.75rem',lineHeight:'calc(1 / .75)',color:'var(--muted-foreground)'},arrow:{marginLeft:'auto',color:'var(--muted-foreground)'},anchor:{width:'var(--anchor-width)',minWidth:'14rem'},fullRound:{borderRadius:'calc(infinity * 1px)'},w44:{width:'11rem'},w56:{width:'14rem'}});
const registryMap={'w-fit':registryStyles.fit,'flex flex-wrap justify-center gap-2':registryStyles.wrap,'w-fit capitalize':[registryStyles.fit,registryStyles.capitalize],'min-w-40':registryStyles.min40,'min-w-56':registryStyles.min56,'flex items-center justify-between gap-4':registryStyles.row,'h-12 justify-start px-2 md:max-w-[200px] style-sera:font-normal style-sera:tracking-normal style-sera:normal-case':registryStyles.account,'rounded-lg':registryStyles.round,'grid flex-1 text-left text-sm leading-tight':registryStyles.details,'truncate font-semibold':[registryStyles.truncate,registryStyles.semibold],'truncate text-xs text-muted-foreground':[registryStyles.truncate,registryStyles.description],'ml-auto text-muted-foreground':registryStyles.arrow,'w-(--anchor-width) min-w-56':registryStyles.anchor,'rounded-full':registryStyles.fullRound,'w-44':registryStyles.w44,'w-56':registryStyles.w56};
export function dropdownExampleStyle(key:keyof typeof registryMap){return {xstyle:registryMap[key]};}
export function dropdownNativeExampleStyle(key:keyof typeof registryMap){const {className,style}=stylex.props(registryMap[key]);return {className,style};}
