import {IconBrandJavascript,IconCopy,IconCornerDownLeft,IconRefresh} from '@tabler/icons-react';
import TextareaAutosize from 'react-textarea-autosize';
import {officialTextarea,officialBottom,officialTop,officialAuto,officialMono,officialCustom} from '@input-group-customizations';
import {groupCustomization,addonCustomization,inputGroupCustomization} from '@input-group-customizations';
import {SearchIcon,MailIcon,CreditCardIcon,CheckIcon,StarIcon,InfoIcon} from 'lucide-react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput, InputGroupText, InputGroupTextarea } from '@input-group';
const meta = { title: 'Components/Input Group', component: InputGroup, tags: ['parity', 'viewport-390'], decorators: [Story => <main id="parity-root" style={{width:320,display:'grid',gap:16}}><Story /></main>] } satisfies Meta<typeof InputGroup>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Align: Story = { render: () => <>{(['inline-start','inline-end','block-start','block-end'] as const).map(align => <InputGroup key={align}><InputGroupInput aria-label={align} placeholder="Search..." /><InputGroupAddon align={align}><InputGroupText>https://</InputGroupText></InputGroupAddon></InputGroup>)}</> };
export const TextareaStates: Story = { render: () => <>{(['block-start','block-end'] as const).map(align => <InputGroup key={align}><InputGroupTextarea aria-label={align} placeholder="Write a message" /><InputGroupAddon align={align}><InputGroupButton>Send</InputGroupButton></InputGroupAddon></InputGroup>)}</> };
export const Buttons: Story = { render: () => <>{(['xs','sm','icon-xs','icon-sm'] as const).map(size => <InputGroup key={size}><InputGroupInput aria-label={size} /><InputGroupAddon align="inline-end"><InputGroupButton size={size} aria-label="Send">{size.startsWith('icon') ? '+' : 'Send'}</InputGroupButton></InputGroupAddon></InputGroup>)}</> };
export const States: Story = { render: () => <><InputGroup><InputGroupInput disabled aria-label="Disabled" /><InputGroupAddon>Disabled</InputGroupAddon></InputGroup><InputGroup><InputGroupInput aria-invalid aria-label="Invalid" /><InputGroupAddon>Error</InputGroupAddon></InputGroup><InputGroup dir="rtl"><InputGroupInput aria-label="RTL" placeholder="البحث" /><InputGroupAddon align="inline-end">بحث</InputGroupAddon></InputGroup></> };
export const Demo: Story = { render: () => <InputGroup style={{maxWidth:'20rem'}}><InputGroupInput placeholder="Search..." /><InputGroupAddon><SearchIcon /></InputGroupAddon><InputGroupAddon align="inline-end">12 results</InputGroupAddon></InputGroup> };
export const Icon: Story = { render: () => <div style={{display:'grid',width:'100%',maxWidth:'24rem',gap:'1.5rem'}}><InputGroup><InputGroupInput placeholder="Search..." /><InputGroupAddon><SearchIcon /></InputGroupAddon></InputGroup><InputGroup><InputGroupInput type="email" placeholder="Enter your email" /><InputGroupAddon><MailIcon /></InputGroupAddon></InputGroup><InputGroup><InputGroupInput placeholder="Card number" /><InputGroupAddon><CreditCardIcon /></InputGroupAddon><InputGroupAddon align="inline-end"><CheckIcon /></InputGroupAddon></InputGroup><InputGroup><InputGroupInput placeholder="Card number" /><InputGroupAddon align="inline-end"><StarIcon /><InfoIcon /></InputGroupAddon></InputGroup></div> };
export const Text: Story = { render: () => <div style={{display:'grid',width:'100%',maxWidth:'24rem',gap:'1.5rem'}}><InputGroup><InputGroupAddon><InputGroupText>$</InputGroupText></InputGroupAddon><InputGroupInput placeholder="0.00" /><InputGroupAddon align="inline-end"><InputGroupText>USD</InputGroupText></InputGroupAddon></InputGroup><InputGroup><InputGroupAddon><InputGroupText>https://</InputGroupText></InputGroupAddon><InputGroupInput placeholder="example.com" style={{paddingLeft:'.125rem'}} /><InputGroupAddon align="inline-end"><InputGroupText>.com</InputGroupText></InputGroupAddon></InputGroup><InputGroup><InputGroupInput placeholder="Enter your username" /><InputGroupAddon align="inline-end"><InputGroupText>@company.com</InputGroupText></InputGroupAddon></InputGroup><InputGroup><InputGroupTextarea placeholder="Enter your message" /><InputGroupAddon align="block-end"><InputGroupText style={{fontSize:'.75rem',lineHeight:'calc(1 / .75)'}}>120 characters left</InputGroupText></InputGroupAddon></InputGroup></div> };
export const Variants: Story = { render: () => <>{(['default','outline','secondary','ghost','destructive','link'] as const).map(variant=><InputGroup key={variant}><InputGroupInput aria-label={variant}/><InputGroupAddon align="inline-end"><InputGroupButton variant={variant}>{variant}</InputGroupButton></InputGroupAddon></InputGroup>)}</> };
export const InlineStyle: Story = { render: () => <InputGroup style={({isFocusWithin})=>({width:240,color:isFocusWithin?'rgb(255, 0, 0)':'rgb(0, 128, 0)'})}><InputGroupInput aria-label="Styled input" style={({isFocused})=>({fontSize:isFocused?20:18})}/><InputGroupAddon style={{paddingLeft:12}}><InputGroupText style={{fontWeight:700}}>Label</InputGroupText><InputGroupButton style={({isPressed})=>({opacity:isPressed?.5:1})}>Send</InputGroupButton></InputGroupAddon></InputGroup> };

export const Customized: Story = { render: () => <InputGroup {...groupCustomization}><InputGroupInput aria-label='Customized input' {...inputGroupCustomization} /><InputGroupAddon {...addonCustomization}>Prefix</InputGroupAddon></InputGroup> };

export const Textarea: Story = { render: () => <div style={{display:'grid',width:'100%',maxWidth:'28rem',gap:'1rem'}}><InputGroup><InputGroupTextarea id="textarea-code-32" placeholder="console.log('Hello, world!');" {...officialTextarea}/><InputGroupAddon align="block-end" {...officialBottom}><InputGroupText>Line 1, Column 1</InputGroupText><InputGroupButton size="sm" {...officialAuto} variant="default">Run <IconCornerDownLeft/></InputGroupButton></InputGroupAddon><InputGroupAddon align="block-start" {...officialTop}><InputGroupText {...officialMono}><IconBrandJavascript/>script.js</InputGroupText><InputGroupButton {...officialAuto} size="icon-xs"><IconRefresh/></InputGroupButton><InputGroupButton variant="ghost" size="icon-xs"><IconCopy/></InputGroupButton></InputGroupAddon></InputGroup></div> };
export const Custom: Story = { render: () => <div style={{display:'grid',width:'100%',maxWidth:'24rem',gap:'1.5rem'}}><InputGroup><TextareaAutosize data-slot="input-group-control" {...officialCustom} placeholder="Autoresize textarea..."/><InputGroupAddon align="block-end"><InputGroupButton {...officialAuto} size="sm" variant="default">Submit</InputGroupButton></InputGroupAddon></InputGroup></div> };
