import {useRef,useState} from 'react';
import type {Meta,StoryObj} from '@storybook/react-vite';
import {InputOTP,InputOTPGroup,InputOTPSlot,InputOTPSeparator} from '@input-otp';
import {Button} from '@button';
import {otpCustom,otpCustomSlot,otpInputStyle} from '@input-otp-customizations';
import {InputOTPDemo} from './input-otp-examples/demo';
import {InputOTPPattern} from './input-otp-examples/pattern';
import InputOTPWithSeparator from './input-otp-examples/separator';
import {InputOTPDisabled} from './input-otp-examples/disabled';
import InputOTPControlled from './input-otp-examples/controlled';
import {InputOTPInvalid} from './input-otp-examples/invalid';
import {InputOTPFourDigits} from './input-otp-examples/four-digits';
import {InputOTPAlphanumeric} from './input-otp-examples/alphanumeric';
import {InputOTPForm} from './input-otp-examples/form';
import {InputOTPRtl} from './input-otp-examples/rtl';
import * as Registry from './input-otp-examples/registry';
const meta={title:'Components/Input OTP',tags:['parity'],decorators:[Story=><main id="parity-root" className="style-nova"><Story/></main>]} satisfies Meta;
export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <InputOTPDemo/>};
export const Pattern:Story={render:()=> <InputOTPPattern/>};
export const Separator:Story={render:()=> <InputOTPWithSeparator/>};
export const Disabled:Story={render:()=> <InputOTPDisabled/>};
export const Controlled:Story={render:()=> <InputOTPControlled/>};
export const Invalid:Story={render:()=> <InputOTPInvalid/>};
export const FourDigits:Story={render:()=> <InputOTPFourDigits/>};
export const Alphanumeric:Story={render:()=> <InputOTPAlphanumeric/>};
export const Form:Story={tags:['viewport-390'],render:()=> <InputOTPForm/>};
export const Rtl:Story={tags:['viewport-390'],render:()=> <InputOTPRtl/>};
export const RegistrySimple:Story={render:()=> <Registry.InputOTPSimple/>};
export const RegistryPattern:Story={render:()=> <Registry.InputOTPPattern/>};
export const RegistrySeparator:Story={render:()=> <Registry.InputOTPWithSeparator/>};
export const RegistryAlphanumeric:Story={render:()=> <Registry.InputOTPAlphanumeric/>};
export const RegistryDisabled:Story={render:()=> <Registry.InputOTPDisabled/>};
export const RegistryFourDigits:Story={render:()=> <Registry.InputOTPFourDigits/>};
export const RegistryInvalid:Story={render:()=> <Registry.InputOTPInvalid/>};
export const RegistryForm:Story={tags:['viewport-390'],render:()=> <Registry.InputOTPForm/>};
export const Usage:Story={render:()=> <InputOTP maxLength={6}><InputOTPGroup><InputOTPSlot index={0}/><InputOTPSlot index={1}/><InputOTPSlot index={2}/></InputOTPGroup><InputOTPSeparator/><InputOTPGroup><InputOTPSlot index={3}/><InputOTPSlot index={4}/><InputOTPSlot index={5}/></InputOTPGroup></InputOTP>};
function CustomExample(){const[gap,setGap]=useState(12),[custom,setCustom]=useState(true);const ref=useRef<HTMLInputElement>(null);return <><Button onPress={()=>setGap(value=>value===12?16:12)}>Change spacing</Button><Button onPress={()=>setCustom(value=>!value)}>Toggle customization</Button><Button onPress={()=>ref.current?.focus()}>Focus input</Button><InputOTP {...otpInputStyle} ref={ref} aria-label="Custom code" maxLength={4} {...(custom?otpCustom(gap):{})} style={{fontSize:18}}><InputOTPGroup>{[0,1].map(index=><InputOTPSlot key={index} {...otpCustomSlot} style={{height:42}} index={index}/>)}</InputOTPGroup><InputOTPSeparator/><InputOTPGroup>{[2,3].map(index=><InputOTPSlot key={index} {...otpCustomSlot} style={{height:42}} index={index}/>)}</InputOTPGroup></InputOTP></>;}
export const Customization:Story={render:()=> <CustomExample/>};
function PasteExample(){const[value,setValue]=useState('');return <><InputOTP aria-label="Paste code" maxLength={6} pasteTransformer={text=>text.replaceAll('-','')} onComplete={setValue}><InputOTPGroup>{[0,1,2,3,4,5].map(index=><InputOTPSlot key={index} index={index}/>)}</InputOTPGroup></InputOTP><output aria-label="Completed">{value}</output></>;}
export const Paste:Story={render:()=> <PasteExample/>};
export const RenderFunction:Story={render:()=> <InputOTP aria-label="Render code" maxLength={3} render={({slots})=><div>{slots.map((slot,index)=><span key={index}>{slot.char??'_'}</span>)}</div>}/>};
