import type { Meta, StoryObj } from '@storybook/react-vite';
import { useState } from 'react';
import { Item, ItemContent, ItemDescription, ItemTitle, ItemGroup, ItemMedia, ItemSeparator } from '@item';
import { InboxIcon } from 'lucide-react';
import { itemDynamic } from '@item-customizations';
import './item-examples/native.css';
import { ItemDemo } from './item-examples/demo';
import { ItemVariant } from './item-examples/variant';
import { ItemSizeDemo } from './item-examples/size';
import { ItemIcon } from './item-examples/icon';
import { ItemAvatar } from './item-examples/avatar';
import { ItemImage } from './item-examples/image';
import { ItemGroupExample } from './item-examples/group';
import { ItemHeaderDemo } from './item-examples/header';
import { ItemLink } from './item-examples/link';
import { ItemDropdown } from './item-examples/dropdown';
import { ItemRtl } from './item-examples/rtl';
import * as Registry from './item-examples/registry';
const meta = {title:'Components/Item',component:Item,tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Item>;
export default meta; type Story=StoryObj<typeof meta>;
export const Usage: Story = { render: () => <Item><ItemContent><ItemTitle>Item</ItemTitle><ItemDescription>Description</ItemDescription></ItemContent></Item> };
function Customized() { const [width,setWidth] = useState(320); const custom = itemDynamic(width); return <Item {...custom} style={{...custom.style,width:width+20}} data-testid="custom-item" onClick={()=>setWidth(width+40)}><ItemTitle style={{fontWeight:700}}>Resize item</ItemTitle></Item>; }
export const Customization: Story = { render: () => <Customized /> };
export const Structure: Story = { render: () => <><ItemGroup><Item variant={null} size={null}><ItemMedia variant={null}><InboxIcon /></ItemMedia><ItemContent><ItemTitle>Null variants</ItemTitle></ItemContent><ItemContent>Second</ItemContent></Item><Item size="xs" data-size="sm" data-variant="muted"><ItemMedia variant="image"><img src="/avatar-controlled.svg" alt="media" /></ItemMedia><ItemContent><ItemDescription><a href="#">Direct</a><span><a href="#">Nested</a></span></ItemDescription></ItemContent></Item><ItemSeparator /><Item size="xs"><ItemContent>First</ItemContent><span data-slot="item-content">Native second</span></Item></ItemGroup><Item href={undefined}><ItemTitle>Undefined href still uses Link</ItemTitle></Item></> };
export const Demo: Story = { render: () => <ItemDemo /> };
export const Variant: Story = { render: () => <ItemVariant /> };
export const Size: Story = { render: () => <ItemSizeDemo /> };
export const Icon: Story = { render: () => <ItemIcon /> };
export const Avatar: Story = {tags: ['viewport-390'], render: () => <ItemAvatar /> };
export const Image: Story = { render: () => <ItemImage /> };
export const Group: Story = { render: () => <ItemGroupExample /> };
export const Header: Story = { render: () => <ItemHeaderDemo /> };
export const Link: Story = { render: () => <ItemLink /> };
export const Dropdown: Story = { render: () => <ItemDropdown /> };
export const Rtl: Story = { render: () => <ItemRtl /> };
export const RegistryDefaultVariantItems: Story = { render: () => <Registry.DefaultVariantItems /> };
export const RegistryOutlineVariantItems: Story = { render: () => <Registry.OutlineVariantItems /> };
export const RegistryMutedVariantItems: Story = { render: () => <Registry.MutedVariantItems /> };
export const RegistryDefaultVariantItemsSmall: Story = { render: () => <Registry.DefaultVariantItemsSmall /> };
export const RegistryOutlineVariantItemsSmall: Story = { render: () => <Registry.OutlineVariantItemsSmall /> };
export const RegistryMutedVariantItemsSmall: Story = { render: () => <Registry.MutedVariantItemsSmall /> };
export const RegistryDefaultVariantItemsExtraSmall: Story = { render: () => <Registry.DefaultVariantItemsExtraSmall /> };
export const RegistryOutlineVariantItemsExtraSmall: Story = { render: () => <Registry.OutlineVariantItemsExtraSmall /> };
export const RegistryMutedVariantItemsExtraSmall: Story = { render: () => <Registry.MutedVariantItemsExtraSmall /> };
export const RegistryDefaultLinkItems: Story = { render: () => <Registry.DefaultLinkItems /> };
export const RegistryOutlineLinkItems: Story = { render: () => <Registry.OutlineLinkItems /> };
export const RegistryMutedLinkItems: Story = { render: () => <Registry.MutedLinkItems /> };
export const RegistryDefaultItemGroup: Story = { render: () => <Registry.DefaultItemGroup /> };
export const RegistryOutlineItemGroup: Story = { render: () => <Registry.OutlineItemGroup /> };
export const RegistryMutedItemGroup: Story = { render: () => <Registry.MutedItemGroup /> };
export const RegistryItemSeparatorExample: Story = { render: () => <Registry.ItemSeparatorExample /> };
export const RegistryItemHeaderExamples: Story = { render: () => <Registry.ItemHeaderExamples /> };
export const RegistryItemFooterExamples: Story = { render: () => <Registry.ItemFooterExamples /> };
export const RegistryItemHeaderAndFooterExamples: Story = { render: () => <Registry.ItemHeaderAndFooterExamples /> };
export const RegistryDefaultVariantItemsWithImage: Story = { render: () => <Registry.DefaultVariantItemsWithImage /> };
export const RegistryOutlineVariantItemsWithImage: Story = { render: () => <Registry.OutlineVariantItemsWithImage /> };
export const RegistryOutlineVariantItemsWithImageSmall: Story = { render: () => <Registry.OutlineVariantItemsWithImageSmall /> };
export const RegistryOutlineVariantItemsWithImageExtraSmall: Story = { render: () => <Registry.OutlineVariantItemsWithImageExtraSmall /> };
export const RegistryMutedVariantItemsWithImage: Story = { render: () => <Registry.MutedVariantItemsWithImage /> };
