import {useState,type CSSProperties} from 'react';
import type {Meta,StoryObj} from '@storybook/react-vite';
import {Marker,MarkerContent,MarkerIcon} from '@marker';
import {Button} from '@button';
import {CheckIcon} from 'lucide-react';
import {markerCustom,markerCustomIcon,markerHelper} from '@marker-customizations';
import {MarkerDemo} from './marker-examples/demo';
import {MarkerVariantsDemo} from './marker-examples/variants';
import {MarkerStatusDemo} from './marker-examples/status';
import {MarkerShimmerDemo} from './marker-examples/shimmer';
import {MarkerSeparatorDemo} from './marker-examples/separator';
import {MarkerBorderDemo} from './marker-examples/border';
import {MarkerIconDemo} from './marker-examples/icon';
import {MarkerLinkButtonDemo} from './marker-examples/link-button';
import * as Registry from './marker-examples/registry';
const meta={title:'Components/Marker',component:Marker,tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Marker>;
export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <MarkerDemo/>};
export const Variants:Story={render:()=> <MarkerVariantsDemo/>};
export const Status:Story={render:()=> <MarkerStatusDemo/>};
export const Shimmer:Story={render:()=> <MarkerShimmerDemo/>};
export const Separator:Story={render:()=> <MarkerSeparatorDemo/>};
export const Border:Story={render:()=> <MarkerBorderDemo/>};
export const Icon:Story={render:()=> <MarkerIconDemo/>};
export const LinkButton:Story={render:()=> <MarkerLinkButtonDemo/>};
export const RegistryMarkers:Story={render:()=> <Registry.MarkerExample/>};
export const RegistryBorder:Story={render:()=> <Registry.MarkerBorder/>};
export const RegistrySeparator:Story={render:()=> <Registry.MarkerSeparator/>};
export const RegistryAccordion:Story={render:()=> <Registry.MarkerAccordion/>};
export const Usage:Story={render:()=> <Marker><MarkerIcon><CheckIcon/></MarkerIcon><MarkerContent>Completed</MarkerContent></Marker>};
export const Rtl:Story={render:()=> <div dir="rtl"><MarkerDemo/></div>};
function CustomExample(){const[gap,setGap]=useState(12);const[count,setCount]=useState(0);return <><Button onPress={()=>setGap(gap===12?20:12)}>Change gap</Button><Marker {...markerCustom(gap)} style={{'--marker-gap':`${gap}px`,padding:12} as CSSProperties} render={props=><button {...props} type="button" onClick={()=>setCount(count+1)}/>}><MarkerIcon {...markerCustomIcon}><CheckIcon/></MarkerIcon><MarkerContent>Custom {count}</MarkerContent></Marker><Marker {...markerHelper}>Helper styles</Marker></>;}
export const Customization:Story={render:()=> <CustomExample/>};

export const RegistryDrawer:Story={render:()=> <Registry.MarkerDrawer/>};
export const RegistryDrawerDefault:Story={render:()=> <Registry.MarkerDrawer variant="default"/>};
export const RegistryDrawerBorder:Story={render:()=> <Registry.MarkerDrawer variant="border"/>};
