import { awaitStoryState } from './story-readiness';
import { MessageScrollerGroupChat as MessageScrollerGroupChatExample } from './official-examples/message-scroller-group-chat';
import { MessageScrollerOpeningPosition as MessageScrollerOpeningPositionExample } from './official-examples/message-scroller-opening-position';
import { MessageScrollerLoadHistory as MessageScrollerLoadHistoryExample } from './official-examples/message-scroller-load-history';
import { MessageScrollerVisibility as MessageScrollerVisibilityExample } from './official-examples/message-scroller-visibility';
import { MessageScrollerCommands as MessageScrollerCommandsExample } from './official-examples/message-scroller-commands';
import type { Meta } from '@storybook/react-vite';
import { BadgeVariants as Example5 } from './official-examples/badge-variants';
import { BadgeAsLink as Example6 } from './official-examples/badge-link';
import Example8 from './official-examples/button-demo';
import Example9 from './official-examples/button-size';
import Example10 from './official-examples/button-default';
import Example11 from './official-examples/button-outline';
import Example12 from './official-examples/button-secondary';
import Example13 from './official-examples/button-ghost';
import Example14 from './official-examples/button-destructive';
import Example15 from './official-examples/button-link';
import Example16 from './official-examples/button-icon';
import Example17 from './official-examples/button-with-icon';
import Example18 from './official-examples/button-rounded';
import Example19 from './official-examples/button-spinner';
import { ButtonRtl as Example21 } from './official-examples/button-rtl';
import { InputGroupInlineStart as Example25 } from './official-examples/input-group-inline-start';
import { InputGroupInlineEnd as Example26 } from './official-examples/input-group-inline-end';
import { InputGroupBlockStart as Example27 } from './official-examples/input-group-block-start';
import { InputGroupBlockEnd as Example28 } from './official-examples/input-group-block-end';
import Example29 from './official-examples/input-group-button';
import { InputGroupKbd as Example30 } from './official-examples/input-group-kbd';
import { InputGroupDropdown as Example31 } from './official-examples/input-group-dropdown';
import Example32 from './official-examples/input-group-spinner';
import { InputGroupRtl as Example33 } from './official-examples/input-group-rtl';
import { InputDemo as Example34 } from './official-examples/input-demo';
import { InputBasic as Example35 } from './official-examples/input-basic';
import { InputField as Example36 } from './official-examples/input-field';
import { InputFieldgroup as Example37 } from './official-examples/input-fieldgroup';
import { InputDisabled as Example38 } from './official-examples/input-disabled';
import { InputInvalid as Example39 } from './official-examples/input-invalid';
import { InputFile as Example40 } from './official-examples/input-file';
import { InputInline as Example41 } from './official-examples/input-inline';
import { InputGrid as Example42 } from './official-examples/input-grid';
import { InputRequired as Example43 } from './official-examples/input-required';
import { InputBadge as Example44 } from './official-examples/input-badge';
import { InputInputGroup as Example45 } from './official-examples/input-input-group';
import { InputButtonGroup as Example46 } from './official-examples/input-button-group';
import { InputForm as Example47 } from './official-examples/input-form';
import { InputRtl as Example48 } from './official-examples/input-rtl';
import { TextareaField as Example58 } from './official-examples/textarea-field';
import { TextareaDisabled as Example59 } from './official-examples/textarea-disabled';
import { TextareaInvalid as Example60 } from './official-examples/textarea-invalid';
import Example61 from './official-examples/textarea-rtl';
export default { title: 'Official demos', tags: ['parity'], decorators: [Story => <main id="parity-root"><Story /></main>] } satisfies Meta;
export const BadgeVariants = { parameters: { originalExample: 'badge-variants' }, render: () => <Example5 /> };
export const BadgeLink = { parameters: { originalExample: 'badge-link' }, render: () => <Example6 /> };
export const ButtonDemo = { tags: ['viewport-390'], parameters: { originalExample: 'button-demo' }, render: () => <Example8 /> };
export const ButtonSize = { tags: ['viewport-390'], parameters: { originalExample: 'button-size' }, render: () => <Example9 /> };
export const ButtonDefault = { parameters: { originalExample: 'button-default' }, render: () => <Example10 /> };
export const ButtonOutline = { parameters: { originalExample: 'button-outline' }, render: () => <Example11 /> };
export const ButtonSecondary = { parameters: { originalExample: 'button-secondary' }, render: () => <Example12 /> };
export const ButtonGhost = { parameters: { originalExample: 'button-ghost' }, render: () => <Example13 /> };
export const ButtonDestructive = { parameters: { originalExample: 'button-destructive' }, render: () => <Example14 /> };
export const ButtonLink = { parameters: { originalExample: 'button-link' }, render: () => <Example15 /> };
export const ButtonIcon = { parameters: { originalExample: 'button-icon' }, render: () => <Example16 /> };
export const ButtonWithIcon = { parameters: { originalExample: 'button-with-icon' }, render: () => <Example17 /> };
export const ButtonRounded = { parameters: { originalExample: 'button-rounded' }, render: () => <Example18 /> };
export const ButtonSpinner = { parameters: { originalExample: 'button-spinner' }, render: () => <Example19 /> };
export const ButtonRtl = { tags: ['viewport-390'], parameters: { originalExample: 'button-rtl' }, render: () => <Example21 /> };
export const InputGroupInlineStart = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-inline-start' }, render: () => <Example25 /> };
export const InputGroupInlineEnd = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-inline-end' }, render: () => <Example26 /> };
export const InputGroupBlockStart = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-block-start' }, render: () => <Example27 /> };
export const InputGroupBlockEnd = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-block-end' }, render: () => <Example28 /> };
export const InputGroupButton = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-button' }, render: () => <Example29 /> };
export const InputGroupKbd = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-kbd' }, render: () => <Example30 /> };
export const InputGroupDropdown = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-dropdown' }, render: () => <Example31 /> };
export const InputGroupSpinner = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-spinner' }, render: () => <Example32 /> };
export const InputGroupRtl = { tags: ['viewport-390'], parameters: { originalExample: 'input-group-rtl' }, render: () => <Example33 /> };
export const InputDemo = { tags: ['viewport-390'], parameters: { originalExample: 'input-demo' }, render: () => <Example34 /> };
export const InputBasic = { tags: ['viewport-390'], parameters: { originalExample: 'input-basic' }, render: () => <Example35 /> };
export const InputField = { tags: ['viewport-390'], parameters: { originalExample: 'input-field' }, render: () => <Example36 /> };
export const InputFieldgroup = { tags: ['viewport-390'], parameters: { originalExample: 'input-fieldgroup' }, render: () => <Example37 /> };
export const InputDisabled = { tags: ['viewport-390'], parameters: { originalExample: 'input-disabled' }, render: () => <Example38 /> };
export const InputInvalid = { tags: ['viewport-390'], parameters: { originalExample: 'input-invalid' }, render: () => <Example39 /> };
export const InputFile = { tags: ['viewport-390'], parameters: { originalExample: 'input-file' }, render: () => <Example40 /> };
export const InputInline = { tags: ['viewport-390'], parameters: { originalExample: 'input-inline' }, render: () => <Example41 /> };
export const InputGrid = { tags: ['viewport-390'], parameters: { originalExample: 'input-grid' }, render: () => <Example42 /> };
export const InputRequired = { tags: ['viewport-390'], parameters: { originalExample: 'input-required' }, render: () => <Example43 /> };
export const InputBadge = { tags: ['viewport-390'], parameters: { originalExample: 'input-badge' }, render: () => <Example44 /> };
export const InputInputGroup = { tags: ['viewport-390'], parameters: { originalExample: 'input-input-group' }, render: () => <Example45 /> };
export const InputButtonGroup = { tags: ['viewport-390'], parameters: { originalExample: 'input-button-group' }, render: () => <Example46 /> };
export const InputForm = { tags: ['viewport-390'], parameters: { originalExample: 'input-form' }, render: () => <Example47 /> };
export const InputRtl = { tags: ['viewport-390'], parameters: { originalExample: 'input-rtl' }, render: () => <Example48 /> };
export const TextareaField = { tags: ['viewport-390'], parameters: { originalExample: 'textarea-field' }, render: () => <Example58 /> };
export const TextareaDisabled = { tags: ['viewport-390'], parameters: { originalExample: 'textarea-disabled' }, render: () => <Example59 /> };
export const TextareaInvalid = { tags: ['viewport-390'], parameters: { originalExample: 'textarea-invalid' }, render: () => <Example60 /> };
export const TextareaRtl = { tags: ['viewport-390'], parameters: { originalExample: 'textarea-rtl' }, render: () => <Example61 /> };

export const MessageScrollerCommands = { parameters: { originalExample: 'message-scroller-commands' }, render: () => <MessageScrollerCommandsExample /> };

export const MessageScrollerVisibility = { parameters: { originalExample: 'message-scroller-visibility' }, render: () => <MessageScrollerVisibilityExample /> };

export const MessageScrollerLoadHistory = { parameters: { originalExample: 'message-scroller-load-history' }, render: () => <MessageScrollerLoadHistoryExample /> };

export const MessageScrollerOpeningPosition = { decorators: [awaitStoryState(() => {
  const viewport = document.querySelector<HTMLElement>('#parity-root [data-slot="message-scroller-viewport"]');
  const content = document.querySelector<HTMLElement>('#parity-root [data-slot="message-scroller-content"]');
  const anchor = document.querySelector<HTMLElement>('#parity-root [data-message-id="open-3"]');
  if (!viewport || !content || !anchor || viewport.hasAttribute('data-autoscrolling') || viewport.hasAttribute('data-pending-scroll')) return false;
  const margin = parseFloat(getComputedStyle(content).paddingTop) + 64;
  return Math.abs(anchor.getBoundingClientRect().top - viewport.getBoundingClientRect().top - margin) < 0.5;
})], parameters: { originalExample: 'message-scroller-opening-position' }, render: () => <MessageScrollerOpeningPositionExample /> };

export const MessageScrollerGroupChat = { parameters: { originalExample: 'message-scroller-group-chat' }, render: () => <MessageScrollerGroupChatExample /> };
