import type {Meta,StoryObj} from '@storybook/react-vite';
import {Popover,PopoverTrigger,PopoverTitle,PopoverHeader,PopoverDescription} from '@popover';
import {Button} from '@button';
import Demo from './popover-examples/demo';
import {PopoverBasic} from './popover-examples/basic';
import {PopoverAlignments} from './popover-examples/alignments';
import {PopoverForm} from './popover-examples/form';
import {PopoverRtl} from './popover-examples/rtl';
import * as Registry from './popover-examples/registry';
import {customized} from '@popover-customizations';
const meta={title:'Components/Popover',component:Popover,tags:['parity','viewport-390'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Popover>;
export default meta;type Story=StoryObj<typeof meta>;
export const DemoExample:Story={name:'Demo',render:()=> <Demo/>};
export const Basic:Story={render:()=> <PopoverBasic/>};
export const Alignments:Story={render:()=> <PopoverAlignments/>};
export const Form:Story={render:()=> <PopoverForm/>};
export const Rtl:Story={render:()=> <PopoverRtl/>};
export const RegistryBasic:Story={render:()=> <Registry.PopoverBasic/>};
export const RegistrySides:Story={render:()=> <Registry.PopoverSides/>};
export const RegistryForm:Story={render:()=> <Registry.PopoverWithForm/>};
export const RegistryAlignments:Story={render:()=> <Registry.PopoverAlignments/>};
export const InDialog:Story={render:()=> <Registry.PopoverInDialog/>};
export const Customized:Story={render:()=> <PopoverTrigger><Button>Custom</Button><Popover data-parity-portal {...customized}><PopoverHeader><PopoverTitle>Custom</PopoverTitle><PopoverDescription>Description</PopoverDescription></PopoverHeader></Popover></PopoverTrigger>};
export const DefaultOpen:Story={render:()=> <PopoverTrigger defaultOpen><Button>Open</Button><Popover data-parity-portal><PopoverTitle>Default open</PopoverTitle></Popover></PopoverTrigger>};
export const Callback:Story={render:()=> <PopoverTrigger><Button>Open</Button><Popover data-parity-portal style={({isEntering})=>({opacity:isEntering?.5:1})}>{({placement})=> <PopoverTitle>{placement}</PopoverTitle>}</Popover></PopoverTrigger>};
