import type {Meta,StoryObj} from '@storybook/react-vite';
import {Questionnaire} from '@questionnaire';
import * as Registry from './questionnaire-examples/registry';
import {QuestionnaireDemo} from './questionnaire-examples/demo';
import {QuestionnaireMultiple} from './questionnaire-examples/multiple';
import {QuestionnaireFreeform} from './questionnaire-examples/freeform';
import {QuestionnaireSkipExample} from './questionnaire-examples/skip';
import {QuestionnaireShortcuts} from './questionnaire-examples/shortcuts';
import {QuestionnaireValidation} from './questionnaire-examples/validation';
import {QuestionnaireControlled} from './questionnaire-examples/controlled';
import {QuestionnaireResume} from './questionnaire-examples/resume';
import {QuestionnaireConditional} from './questionnaire-examples/conditional';
import {QuestionnaireNavigationState} from './questionnaire-examples/navigation-state';
import {QuestionnaireProgressExample} from './questionnaire-examples/progress';
import {QuestionnaireAnimated} from './questionnaire-examples/animated';
import {QuestionnaireCard} from './questionnaire-examples/card';
import {QuestionnaireDialog} from './questionnaire-examples/dialog';
const meta={title:'Components/Questionnaire',component:Questionnaire,tags:['parity'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Questionnaire>;export default meta;type Story=StoryObj<typeof meta>;
export const Demo:Story={render:()=> <QuestionnaireDemo/>};
export const Multiple:Story={render:()=> <QuestionnaireMultiple/>};
export const Freeform:Story={render:()=> <QuestionnaireFreeform/>};
export const Skip:Story={render:()=> <QuestionnaireSkipExample/>};
export const Shortcuts:Story={render:()=> <QuestionnaireShortcuts/>};
export const Validation:Story={render:()=> <QuestionnaireValidation/>};
export const Controlled:Story={render:()=> <QuestionnaireControlled/>};
export const Resume:Story={render:()=> <QuestionnaireResume/>};
export const Conditional:Story={render:()=> <QuestionnaireConditional/>};
export const NavigationState:Story={render:()=> <QuestionnaireNavigationState/>};
export const Progress:Story={render:()=> <QuestionnaireProgressExample/>};
export const Animated:Story={render:()=> <QuestionnaireAnimated/>};
export const Card:Story={render:()=> <QuestionnaireCard/>};
export const Dialog:Story={render:()=> <QuestionnaireDialog/>};
export const RegistryDisabled:Story={render:()=> <Registry.QuestionnaireDisabled/>};
export const RegistryNoDescription:Story={render:()=> <Registry.QuestionnaireNoDescription/>};
export const RegistryStandalone:Story={render:()=> <Registry.QuestionnaireStandalone/>};
export const RegistryCard:Story={render:()=> <Registry.QuestionnaireCard/>};
export const RegistryDialog:Story={render:()=> <Registry.QuestionnaireDialog/>};
export const Rtl:Story={render:()=> <div dir="rtl"><QuestionnaireDemo/></div>};
export const Mobile:Story={tags:['viewport-390'],render:()=> <QuestionnaireFreeform/>};
import {QuestionnaireCustomization} from './questionnaire-examples/customization';
export const Customization:Story={render:()=> <QuestionnaireCustomization/>};
