import type {Meta,StoryObj} from '@storybook/react-vite';
import {ModalContext} from 'react-aria-components';
import {Sheet,SheetContent,SheetTrigger,SheetHeader,SheetTitle,SheetDescription,SheetFooter,SheetClose} from '@sheet';
import {Button} from '@button';
import Demo from './sheet-examples/demo';
import Sides from './sheet-examples/side';
import NoClose from './sheet-examples/no-close-button';
import {SheetRtl} from './sheet-examples/rtl';
import * as Registry from './sheet-examples/registry';
import {customized} from '@sheet-customizations';
const meta={title:'Components/Sheet',component:Sheet,args:{children:null},tags:['parity','viewport-390'],decorators:[Story=><main id="parity-root"><Story/></main>]} satisfies Meta<typeof Sheet>;
export default meta;type Story=StoryObj<typeof meta>;
export const DemoExample:Story={name:'Demo',render:()=> <Demo/>};
export const Side:Story={render:()=> <Sides/>};
export const NoCloseButton:Story={render:()=> <NoClose/>};
export const Rtl:Story={render:()=> <SheetRtl/>};
export const RegistryForm:Story={render:()=> <Registry.SheetWithForm/>};
export const RegistryNoClose:Story={render:()=> <Registry.SheetNoCloseButton/>};
export const RegistrySides:Story={render:()=> <Registry.SheetWithSides/>};
export const Usage:Story={render:()=> <SheetTrigger><Button>Open</Button><SheetContent data-parity-portal><SheetHeader><SheetTitle>Are you absolutely sure?</SheetTitle><SheetDescription>This action cannot be undone.</SheetDescription></SheetHeader><SheetFooter><SheetClose>Close</SheetClose></SheetFooter></SheetContent></SheetTrigger>};
export const DefaultOpen:Story={render:()=> <SheetTrigger defaultOpen><Button>Open</Button><Sheet data-parity-portal><SheetTitle>Default open</SheetTitle></Sheet></SheetTrigger>};
export const Context:Story={render:()=> <ModalContext.Provider value={{isOpen:true}}><Sheet data-parity-portal><SheetTitle>Context open</SheetTitle></Sheet></ModalContext.Provider>};
export const Customized:Story={render:()=> <SheetTrigger><Button>Custom</Button><Sheet data-parity-portal {...customized}><SheetHeader><SheetTitle>Custom</SheetTitle></SheetHeader><SheetFooter><SheetClose style={({isPressed})=>({opacity:isPressed?.5:1})}>Close</SheetClose></SheetFooter></Sheet></SheetTrigger>};
