import type{Meta,StoryObj}from"@storybook/react-vite";
import{I18nProvider}from"react-aria-components";
import{TypographyBlockquote}from"./typography-examples/typography-blockquote";
import{TypographyDemo}from"./typography-examples/typography-demo";
import{TypographyH1}from"./typography-examples/typography-h1";
import{TypographyH2}from"./typography-examples/typography-h2";
import{TypographyH3}from"./typography-examples/typography-h3";
import{TypographyH4}from"./typography-examples/typography-h4";
import{TypographyInlineCode}from"./typography-examples/typography-inline-code";
import{TypographyLarge}from"./typography-examples/typography-large";
import{TypographyLead}from"./typography-examples/typography-lead";
import{TypographyList}from"./typography-examples/typography-list";
import{TypographyMuted}from"./typography-examples/typography-muted";
import{TypographyP}from"./typography-examples/typography-p";
import{TypographyRtl}from"./typography-examples/typography-rtl";
import{TypographySmall}from"./typography-examples/typography-small";
import{TypographyTable}from"./typography-examples/typography-table";
const meta={title:"Components/Typography",tags:["parity","viewport-390"],decorators:[Story=><main id="parity-root"><div><Story/></div></main>]}satisfies Meta;export default meta;type Story=StoryObj<typeof meta>;
export const Blockquote:Story={render:()=> <TypographyBlockquote/>};
export const Demo:Story={render:()=> <TypographyDemo/>};
export const H1:Story={render:()=> <TypographyH1/>};
export const H2:Story={render:()=> <TypographyH2/>};
export const H3:Story={render:()=> <TypographyH3/>};
export const H4:Story={render:()=> <TypographyH4/>};
export const InlineCode:Story={render:()=> <TypographyInlineCode/>};
export const Large:Story={render:()=> <TypographyLarge/>};
export const Lead:Story={render:()=> <TypographyLead/>};
export const List:Story={render:()=> <TypographyList/>};
export const Muted:Story={render:()=> <TypographyMuted/>};
export const P:Story={render:()=> <TypographyP/>};
export const Rtl:Story={decorators: [Story => <I18nProvider locale="ar"><Story /></I18nProvider>], parameters: { originalExample: "typography-rtl" }, render: () => <TypographyRtl/>};
export const Small:Story={render:()=> <TypographySmall/>};
export const Table:Story={render:()=> <TypographyTable/>};
import{TypographyConditions}from'./typography-conditions';
export const Conditions:Story={render:()=> <TypographyConditions/>};
import{typographyNative}from'@typography-customizations';
export const NativeOverrides:Story={render:()=> <h1 {...typographyNative()}>Dynamic styles with native priority</h1>};
